---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

Loading packages

```{r message=FALSE, warning=FALSE, include=FALSE}

.libPaths()

library(lubridate)
library(tidyverse)
library(utils)
library(data.table)
library(ggrepel)
library(RColorBrewer)
```


Pulling the most recent data from ecdc
```{r include=FALSE}
ecdc_data <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM", stringsAsFactors = FALSE)
```


Importing 
```{r}
pop_data <- read_csv("pop_data.csv", col_types = "cci")
```



Narrowing to 
```{r include=FALSE}
my_ecdc <- ecdc_data %>% 
  mutate(as_of = dmy(dateRep),
         co_code = as.character(countryterritoryCode)) %>% 
  inner_join(pop_data) %>% 
         mutate(cases_pm = cases * 1000000 / pop_2019,
         deaths_pm = deaths * 1000000 / pop_2019) %>% 
  select(co_code,
         co_name,
         as_of,
         cases,
         cases_pm,
         deaths,
         deaths_pm,
         pop_2019)
  
```


```{r}
oecd_list <- c("AUSTRALIA", "AUSTRIA", "BELGIUM", "CANADA", "CHILE",
"CZECH REPUBLIC", "CZECHIA", "DENMARK", "ESTONIA", "FINLAND", "FRANCE",
"GERMANY", "GREECE", "HUNGARY", "ICELAND", "IRELAND", "ISRAEL", "ITALY",
"JAPAN",
"KOREA",
"SOUTH KOREA",
"SOUTH_KOREA",
"LATVIA",
"LITHUANIA",
"LUXEMBOURG",
"MEXICO",
"NETHERLANDS",
"NEW ZEALAND",
"NORWAY",
"POLAND",
"PORTUGAL",
"SLOVAK REPUBLIC",
"SLOVAKIA",
"SLOVENIA",
"SPAIN",
"SWEDEN",
"SWITZERLAND",
"TURKEY",
"UNITED KINGDOM",
"UNITED_KINGDOM",
"UNITED STATES",
"UNITED STATES OF AMERICA",
"UNITED_STATES",
"UNITED_STATES_OF_AMERICA")
```



Building tables
```{r include=FALSE}
my_oecd <- my_ecdc %>% 
  filter(toupper(co_name) %in% oecd_list)
```



```{r}

just_nordics <- my_oecd %>% 
  filter(co_code %in% c("SWE", "FIN", "ISL", "NOR", "DNK")) %>% 
  group_by(co_code) %>% 
  arrange(as_of) %>% 
  mutate(tot_deaths = cumsum(deaths),
         tot_deaths_pm = cumsum(deaths_pm),
         tot_cases = cumsum(cases),
         tot_cases_pm = cumsum(cases_pm)) %>% 
  ungroup()
  

```



```{r}
just_nordics %>% 
  filter(tot_deaths>0) %>% 
  mutate(x_lbl = if_else(as_of == max(as_of), max(as_of), NULL),
         y_lbl = if_else(as_of == max(as_of), tot_deaths_pm, NULL),
         cfr = deaths / cases) %>% 
  ggplot(mapping = aes(x = as_of, y = tot_deaths_pm)) +
  geom_point(mapping = aes(color = co_code, size = cfr)) +
  geom_label_repel(mapping = aes(x = x_lbl, y = y_lbl, color = co_code, label = co_code), na.rm = TRUE) +
  theme(legend.position = "none") +
  labs(title = "Sweden has five to 10 times more COVID-19 deaths than other Nordic countries", x = "Cumulative COVID-19 deaths per million", y = "Date")
```


```{r}
just_nordics %>% 
  filter(tot_cases>0) %>% 
  mutate(x_lbl = if_else(as_of == max(as_of), max(as_of), NULL),
         y_lbl = if_else(as_of == max(as_of), tot_cases_pm, NULL)) %>% 
  ggplot(mapping = aes(x = as_of, y = tot_cases_pm)) +
  geom_point(mapping = aes(color = co_code, size = cases_pm)) +
  geom_label_repel(mapping = aes(x = x_lbl, y = y_lbl, color = co_code, label = co_code), na.rm = TRUE) +
  theme(legend.position = "none") +
  labs(title = "Sweden has 30 to 500% more cases per capita than other Nordic countries")
```



```{r include=FALSE}
weekly_oecd <- my_oecd %>% 
  mutate(as_of_week = lubridate::week(as_of)) %>%
  group_by(co_code, as_of_week) %>% 
  summarize(weekly_deaths_pm = sum(deaths_pm),
            weekly_deaths = sum(deaths),
            weekly_cases_pm = sum(cases_pm),
            weekly_cases = sum(cases),
            mean_cases_pm = mean(deaths_pm, na.rm = TRUE),
            mean_deaths_pm = mean(deaths_pm, na.rm = TRUE),
            wk_ending = max(as_of))
```


```{r echo=FALSE}
weekly_oecd %>%
  filter(1 >= abs(lubridate::week(max(wk_ending)) - as_of_week)) %>%
  group_by(co_code) %>% 
  summarize(death_ch_pm = sum(weekly_deaths_pm)) %>% 
  filter(death_ch_pm > median(death_ch_pm)) %>% 
  ggplot() +
  geom_col(mapping = aes(x = reorder(co_code, desc(death_ch_pm)), y = death_ch_pm)) +
  labs(x = "Country code", y = "Deaths the past 2 weeks per 1 mil. pop.", subtitle = str_c("as of", max(weekly_oecd$wk_ending), sep = " "), title = "Deaths over the last two weeks adjusted for population")
```

```{r echo=FALSE}
weekly_oecd %>%
  filter(1 >= abs(lubridate::week(max(wk_ending)) - as_of_week)) %>%
  group_by(co_code) %>% 
  summarize(cases_ch_pm = sum(weekly_cases_pm)) %>% 
  filter(cases_ch_pm > median(cases_ch_pm)) %>% 
  ggplot() +
  geom_col(mapping = aes(x = reorder(co_code, desc(cases_ch_pm)), y = cases_ch_pm)) +
  labs(x = "Country code", y = "Cases the past 2 weeks per 1 mil. pop.", subtitle = str_c("as of", max(weekly_oecd$wk_ending), sep = " "), title = "Cases over the last two weeks adjusted for population")
```


```{r}
my_oecd %>% 
  filter(co_code %in% c("KOR", "USA", "CAN"),
         cases_pm > 0) %>% 
  ggplot(mapping = aes(x = as_of, y = cases_pm, color = co_code)) +
  geom_smooth(size = 2, alpha = 0) +
  labs(color = NULL,
       x = "Date",
       y = "New cases per mil.")

```



```{r echo=FALSE}
total_oecd <- my_oecd %>% 
  group_by(co_code) %>% 
  summarize(total_deaths_pm = sum(deaths_pm),
            total_deaths = sum(deaths),
            total_cases_pm = sum(cases_pm),
            total_cases = sum(cases),
            end_date = max(as_of))
```


```{r echo=FALSE}
total_oecd %>% 
  filter(total_deaths_pm > median(total_oecd$total_deaths_pm)) %>%
  mutate(cfr = total_deaths / total_cases) %>% 
  arrange(desc(total_deaths_pm)) %>% 
  ggplot() +
  geom_col(mapping = aes(x = reorder(co_code, desc(total_deaths_pm)), y = total_deaths_pm, fill = cfr)) +
  labs(x = "Country code", y = "Deaths per 1 mil population")
```


```{r echo=FALSE}
total_oecd %>%
  mutate(cfr = signif(total_deaths / total_cases, 2)) %>% 
  ggplot() +
  geom_label_repel(mapping = aes(x = total_cases_pm, y = total_deaths_pm, label = str_c(co_code, cfr, sep = " "), color = cfr)) +
  labs(x = "Cases per 1 mil population", y = "Deaths per 1 mil population") +
  scale_color_gradientn(colors = c("darkgray", "red"))
```


```{r}
total_oecd
```



```{r}
labelly <- my_oecd %>% 
  group_by(co_code) %>% 
  summarize(as_of = max(as_of), label_death = max(deaths_pm))


my_kor <- my_oecd %>%
  filter(co_code == "KOR") %>%
  select(as_of, cases, deaths)

j <- data.table(d_offset = integer(), cor_offset = double())

for (i in 5:62) {

j <- rbind(j, data.table(d_offset = i, cor_offset = my_kor %>%
    mutate(d_lag = as_of + days(i)) %>%
    left_join(my_kor, by = c("d_lag" = "as_of")) %>% 
    pull(6) %>% 
    cor(x = ., y = my_kor$cases, use = "complete.obs")))
}

j

my_kor %>% 
  mutate(d_as_of = as_of - days(20)) %>% 
  select(deaths, d_as_of) %>%
  full_join((my_kor %>% select(cases, as_of)), by = c("d_as_of" = "as_of")) %>% 
  mutate(week_num = week(d_as_of)) %>%
  group_by(week_num) %>% 
  summarize(death_wk = sum(deaths, na.rm = TRUE),
            case_wk = sum(cases, na.rm = TRUE),
            week_of = median(d_as_of, na.rm = TRUE)) %>% 
  mutate(deaths_ix = death_wk / max(death_wk, na.rm = TRUE),
         cases_ix = case_wk / max(case_wk, na.rm = TRUE)) %>% 
  ggplot(mapping = aes(x = week_of)) + 
  geom_line(mapping = aes(y = deaths_ix), color = "green") +
  geom_line(mapping = aes(y = cases_ix), color = "orange")
  

```


```{r}
raw_labor <- read_csv("nordic_unemp.csv")

nord_labor <- raw_labor %>%
  gather(code, "unemp", "dnk", "fin", "isl", "nor", "swe") %>% 
  mutate(code = toupper(code))
```


```{r}
nord_labor %>% 
  mutate(co_code = code) %>% 
  group_by(co_code) %>%
  filter(!is.na(unemp)) %>% 
  filter(ymd(DATE) %in% c(max(ymd(DATE), na.rm = TRUE), ymd("2020-01-01"))) %>%
  summarize(as_of = max(DATE, na.rm = TRUE), unemp = max(unemp, na.rm = TRUE) - min(unemp, na.rm = TRUE)) %>% 
  left_join(my_oecd) %>% 
  ggplot() +
  geom_label(mapping = aes(x = deaths_pm, y = unemp, color = co_code, label = str_c(co_code))) +
  labs(x = "COVID-19 cases per million", y = str_c("change in unemployment rate from Jan 2020")) +
  theme(legend.position = "none")

  
```