---
title: "R Notebook"
output: html_notebook
---


```{r setup}
knitr::opts_chunk$set(message = FALSE)
library(tidyverse); library(lubridate); library(ggalluvial); library(ggthemes); library(moments); library(ggcorrplot)


```


```{r, echo=FALSE, message=FALSE}


  
  



# airlines_17 <- read_csv(file = 'airlines_17.csv', trim_ws = T)



# airports_17 <- read_csv(file = 'airports_17.csv', trim_ws = T, col_names = c('airport_name', 'airport_iata', 'airport_st'))
```


```{r}
## This converts hmm or c(h, mm) to a metric value h.hh
metric_time <- function(horhm, mm = rep(-1, length(horhm))){
  if(mm < 0){ return(trunc(horhm/100) + (horhm/100 - trunc(horhm/100)) * 5 / 3) }
  else{ return(horhm + mm/60) }
}

```


```{r}
## Make metric month function
metric_month <- function(mo, mo_day){ return(mo + (mo_day - 0.5) / max(mo_day)) }
```



```{r, message=FALSE, warning=FALSE}
## build a test set 

test_17 <- flights %>%
  filter(!is.na(dep_delay)) %>% ## Remove flights that are missing dep_delay
  group_by(month) %>%
  mutate(on_time = dep_delay <= 1, ## This and the next line split the data set into on-time flights...
         ln_delay = if_else(dep_delay > 1, log(dep_delay), NA_real_), ## ...and log-length of delay, if delay
         diff_5mo = abs(5.31 - month), 
         wkday = weekdays(time_hour),
         month_metric = metric_month(month, day),  ## Using my function
         time_metric = metric_time(sched_dep_time), ## Using my function
         diff_21h = abs(21.45 - time_metric)) %>%
  ungroup() %>%
  select(-(1:5), -(7:9), -(11:12), -(hour:minute)) %>%
  left_join(weather, by = c('time_hour', 'origin'))

```


```{r}
## Build a correlogram
test_17 %>%
  filter(carrier == 'B6') %>%
  select(on_time:ln_delay,
         air_time:distance,
         month_metric:time_metric,
         temp:visib) %>%
  cor(use = "pairwise.complete.obs") %>%
  round(1) %>%
  ggcorrplot(lab = TRUE,
             #method="circle",
             type = "lower",
             lab_size = 3,
             colors = c("orange", "white", "dodgerblue"), 
             title="Correlogram of flight and weather data", 
             ggtheme = theme_bw())
  
    
    



```


```{r}

test_17 %>%
  filter(carrier == 'B6', !is.na(dewp)) %>%
  ggplot(mapping = aes(x = temp, y = dewp)) +
  geom_smooth(method = 'lm', color = 'darkgray', fill = 'darkgray', alpha = 0.8) +
  geom_count(color = 'dodgerblue', show.legend = F, na.rm = T) +
  theme_bw() +
  labs(title = "The correlation between temperature and dewpoint makes using both redundant",
       x = "temperature in degrees",
       y = "dewpoint in degrees")


  
```



```{r}
test_17 %>%
  mutate(is_b6 = (carrier == 'B6')) %>%
  mutate(month_metric = round(month_metric, 1)) %>%
  group_by(month_metric, is_b6) %>%
  summarize(mean_on_time = mean(on_time)) %>%
  group_by(month_metric) %>%
  mutate(b6_v_others = if_else(2 * is_b6 == 2,
                                 mean_on_time - mean(mean_on_time),
                                 mean(mean_on_time) - mean_on_time)) %>%
  summarize(b6_factor = sum(b6_v_others)) %>%
  ggplot(mapping = aes(x = month_metric - 0.5, ymax = b6_factor, ymin = 0)) +
  geom_ribbon(fill = 'dodgerblue') +
  scale_x_continuous(labels = month.abb[1:12], breaks = 1:12) +
  theme_bw() +
  labs(title = 'JetBlue lags in on-time departures all year but especially in summer months',
       x = 'date',
       y = 'on-time departures vs competitors')

  
  
```

```{r}

test_17 %>%
  filter(carrier %in% c('AA', 'B6', 'DL', 'UA') &
           !is.na(ln_delay)) %>%
  group_by(carrier) %>%
  summarize(q1 = quantile(dep_delay, 0.25),
            q3 = quantile(dep_delay, 0.75)) %>%
  ggplot(mapping = aes(x = q1, xend = q3, y = carrier)) +
  geom_dumbbell(colour_x = "dodgerblue",
                size = 2,
                size_x = 4,
                size_xend = 4,
                colour_xend = "darkblue",
                colour = 'dodgerblue') +
  labs(x = NULL,
       y = NULL,
       title = "Departure delay interquartile range is longest for JetBlue on both ends") +
  scale_x_continuous(label = minutes) +
  theme_excel_new() +
  theme(plot.title = element_text(face = "bold"),
              panel.grid.major.x=element_line(),
              axis.ticks=element_blank(),
              panel.border=element_blank())
  
```



```{r}
test_17 %>%
  filter(month_metric > 6 &
           month_metric < 9) %>%
  mutate(is_b6 = (carrier == "B6")) %>%
  ggplot(mapping = aes(x = ln_delay)) +
  geom_density(aes(fill = is_b6), alpha=0.7, na.rm = T) +
  labs(title = "JetBlue summer flights also have longer delays than competitors",
       x = "natural log of delay",
       fill="Carrier") +
  scale_fill_manual(values = c('black', 'dodgerblue'),
                    aesthetics = 'fill',
                    labels = c('Competitors', 'JetBlue'),
                    guide = guide_legend(reverse = T))


```



```{r}
## Build Linear model using month, time, and weekday data
mdl <- lm(data = test_17, formula = ln_delay ~ diff_21h + diff_5mo + wkday) %>%
  summary()

```



```{r}
## Pull out the coefficients and standard error
coefs <- mdl$coefficients %>%
  as_tibble() %>%
  mutate(x_var = row.names(mdl$coefficients)) %>%
  select(5, coef = 1, se = 2)
```


```{r}
## This builds the pred_delay equation
paste(coefs[1, 2], "+",
      coefs[2, 2], "* diff_21h +",
      coefs[3, 2], "* diff_5mo +",
      coefs[4, 2], "* (wkday == 'Monday') +",
      coefs[5, 2], "* (wkday == 'Saturday') +",
      coefs[6, 2], "* (wkday == 'Sunday') +",
      coefs[7, 2], "* (wkday == 'Thursday') +",
      coefs[8, 2], "* (wkday == 'Tuesday') +",
      coefs[9, 2], "* (wkday == 'Wednesday')")

```

```{r}
## Build logit model using month, time, and weekday data
mdl_2 <- glm(data = test_17, formula = on_time ~ diff_21h + diff_5mo + wkday, family = 'binomial') %>%
  summary()

mdl_2
```


```{r}
coefs_2 <- mdl_2$coefficients %>%
  as_tibble() %>%
  mutate(x_var = row.names(mdl$coefficients)) %>%
  select(5, coef = 1, se = 2)
```



```{r}
## This builds the logit for p_on_time
paste(coefs_2[1, 2], "+",
      coefs_2[2, 2], "* diff_21h +",
      coefs_2[3, 2], "* diff_5mo +",
      coefs_2[4, 2], "* (wkday == 'Monday') +",
      coefs_2[5, 2], "* (wkday == 'Saturday') +",
      coefs_2[6, 2], "* (wkday == 'Sunday') +",
      coefs_2[7, 2], "* (wkday == 'Thursday') +",
      coefs_2[8, 2], "* (wkday == 'Tuesday') +",
      coefs_2[9, 2], "* (wkday == 'Wednesday')")
```



```{r}
## Add predicted delay and probability of no delay to test tibble
pred_17 <- test_17 %>%
  mutate(pred_delay = exp(3.85236933552203 +
           -0.0636324279034302 * diff_21h +
           -0.0541743901271069 * diff_5mo +
           -0.0618142578716507 * (wkday == 'Monday') +
           -0.125034427355075 * (wkday == 'Saturday') +
           -0.172379656023462 * (wkday == 'Sunday') +
           -0.108048760292188 * (wkday == 'Thursday') +
           -0.0454143145559025 * (wkday == 'Tuesday') +
           -0.17399920842538 * (wkday == 'Wednesday')),
         p_on_time = 1 / (1 + exp(-(-0.868973986936626 +
                                      0.132485588024036 * diff_21h +
                                      0.0938310236036926 * diff_5mo +
                                      0.152317762763714 * (wkday == 'Monday') +
                                      0.312356993431681 * (wkday == 'Saturday') +
                                      0.323550415257237 * (wkday == 'Sunday') +
                                      0.0979982073199806 * (wkday == 'Thursday') +
                                      0.265313809910303 * (wkday == 'Tuesday') +
                                      0.316247648362565 * (wkday == 'Wednesday')))))

```



```{r}
## Test month ##

cor_df <- tibble(i = 1L, cor_i = 0.001)

for(i in 101:1231) {
  cor_df[i, 1] <- i/100
  cor_df[i, 2] <- cor(abs(i/100 - test_17$month), test_17$ln_delay)
}

cor_df %>%
  arrange(desc(abs(cor_i)))

```


```{r}
## Test time ##

cor_df <- tibble(i = 1L, cor_i = 0.001)

for(i in 900:2300) {
  cor_df[i, 1] <- i/100
  cor_df[i, 2] <- cor(abs(i/100 - test_17$time_metric), test_17$ln_delay, use = 'pairwise.complete.obs')
}

cor_df %>%
  arrange(desc(abs(cor_i)))
```


```{r, message=FALSE}
## With this plot, I wanted to show why I chose to use a difference factor
## rather than just using the time of day variable. Intuitively, the
## reason is that the change from 23:59 to 00:00 is the biggest numerically
## but doesn't mean much in practice

pred_17 %>%
  select(diff_21h, time_metric, pred_delay) %>%
  unique() %>%
  ggplot() +
  geom_point(mapping = aes(time_metric, p_on_time, color = 'time'), size = 1) +
  geom_smooth(aes(time_metric, p_on_time, color = 'time'), method = 'loess') +
  geom_point(mapping = aes(diff_21h, p_on_time, color = 'adj_time'), size = 1) +
  geom_smooth(aes(diff_21h, p_on_time, color = 'adj_time'), method = 'loess') +
  theme_bw()
```


```{r}
kurtosis(test_17$ln_delay, na.rm = T)
skewness(test_17$ln_delay, na.rm = T)
mean(test_17$ln_delay, na.rm = T)
median(test_17$ln_delay, na.rm = T)


ggplot(data = test_17, mapping = aes(ln_delay), fill = 'gray') +
  geom_density(na.rm = T) +
  geom_vline(xintercept = mean(test_17$ln_delay, na.rm = T), color = 'orange', size = 1.5) +
  geom_vline(xintercept = median(test_17$ln_delay, na.rm = T), color = 'dodgerblue', size = 1.5) +
  theme_fivethirtyeight() +
  scale_color_fivethirtyeight(labels = c('dodgerblue', 'orange')) 
  ggtitle('Distribution looks pretty normal')

kurtosis(test_17$dep_delay); skewness(test_17$dep_delay)
```


```{r}

flights_17 %>%
  group_by(carrier) %>%
  summarize(num_flights = n()) %>%
  arrange(desc(num_flights))

flights_wide <- flights %>%
  select(-(1:3),-hour) %>%
  left_join(weather, by = c("time_hour", "origin")) %>%
  select(-(year:hour)) %>%
  left_join(planes, by = 'tailnum') %>%
  left_join(airports, by = c('dest' = 'faa')) %>%
  filter(!is.na(seats) &
           !is.na(dep_delay)) %>%
  mutate(price = seats * 200,
         cost = 15 * distance + (dep_delay > 0) * seats * dep_delay)

getwd()
write_csv(flights_wide, path = 'C:/Users/Mario/Downloads/flights_wide.csv')
```


```{r}
air_fin <- read_csv('air_fin.csv',na = '', col_names = c('carrier', 'year', 'opn_exp', 'opn_inc', 'exp_growth', 'inc_growth'), skip = 1)

air_fin[13:16,1] <- 'United'

air_fin %>%
  filter(!is.na(exp_growth)) %>%
  ggplot() +
  geom_col(mapping = aes(x = year, y = exp_growth, fill = year)) +
  facet_wrap(facets = ~carrier, nrow = 1) +
  theme_excel_new() +
  theme(legend.position = "none") +
  ggtitle('Each airline has experienced cost growth but none more than JetBlue')

airports
  
```

