---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


Loading packages
```{r message=FALSE, warning=FALSE, include=FALSE}



library(lubridate)
library(data.table)
library(tidyr)
library(magrittr)
library(ggplot2)
library(dplyr)
library(jsonlite)
library(ggrepel)
library(stringr)
library(readr)
library(ggthemes)




```


Pulling the most recent data from covidtracking.com...
```{r message=FALSE, warning=FALSE, include=FALSE}
all_data <- "https://covidtracking.com/api/v1/states/daily.json" %>%
  fromJSON() %>%
  as.data.table()
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
print(str_c("Retrieved  ", Sys.time()))
print(str_c("Data as of ", ymd(max(all_data[,date]))))
```



Narrowing data...
```{r Narrow_data, message=FALSE, warning=FALSE, include=FALSE}
my_data <- all_data %>% 
  mutate(as_of = ymd(date),
         tests = positive + negative,
         test_ch = positiveIncrease + negativeIncrease) %>% 
  select(as_of,
         code = state,
         cases = positive,
         case_ch = positiveIncrease,
         death,
         death_ch = deathIncrease,
         tests,
         test_ch) %>% 
  data.table()

```



Adding state population data...
```{r include=FALSE}
st_pop_2019 <- read_csv("st_pop.csv") %>% 
  select(name = 5, pop_2019 = 17) %>% 
  mutate(pop_2019 = as.integer(pop_2019))
```



Building tables...
```{r include=FALSE}
code_names <- data.table(cbind(name = state.name,
                 code = state.abb,
                 region = as.character(state.region),
                 reg_2 = c("South", "Plain and Mountain", "Southwest", "Middle South", "West Coast",
                           "Southwest", "Northeast", "Northeast", "South", "South",
                           
                           "West Coast", "Plain and Mountain", "Midwest", "Midwest", "Midwest",
                           "Plain and Mountain", "Middle South", "South", "Northeast", "Northeast",
                           
                           "Northeast", "Midwest", "Midwest", "South", "Midwest",
                           "Plain and Mountain", "Plain and Mountain", "Southwest", "Northeast", "Northeast",
                           
                           "Southwest", "Northeast", "South", "Plain and Mountain", "Midwest",
                           "Plain and Mountain", "West Coast", "Northeast", "Northeast", "South",
                           
                           "Plain and Mountain", "Middle South", "Southwest", "Plain and Mountain", "Northeast",
                           "South", "West Coast", "Middle South", "Midwest", "Plain and Mountain")))
```


```{r include=FALSE}
test_growth <- code_names %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(my_data) %>% 
  group_by(code) %>% 
  filter(as_of > as_date(ymd_hms(now())) - 7) %>%
  summarize(test_weekly_growth = round((max(tests) - min(tests)) / min(tests), 2),
            tests_weekly_per_mil = signif(((max(tests) - min(tests)) / mean(pop_2019) * 1000000), 3),
            wk_ending = max(as_of)) %>% 
  arrange(desc(test_weekly_growth))
```

```{r include=FALSE}
death_growth <- code_names %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(my_data) %>% 
  group_by(code) %>% 
  filter(as_of > as_date(ymd_hms(now())) - 7) %>%
  summarize(death_weekly_growth = round((max(death) - min(death)) / min(death), 2), death_weekly_per_mil = signif(sum(death_ch) / mean(pop_2019) * 1000000 / 2, 3), wk_ending = max(as_of)) %>% 
  arrange(desc(death_weekly_growth))
```


```{r include=FALSE}
weekly_data <- code_names %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(my_data) %>% 
  mutate(week_num = lubridate::week(as_of)) %>% 
  group_by(code, week_num) %>%
  mutate(weekly_cases = sum(case_ch),
         weekly_deaths = sum(death_ch),
         weekly_tests = sum(test_ch))
  
```


```{r include=FALSE}
case_growth <- code_names %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(my_data) %>% 
  group_by(code) %>% 
  filter(as_of > as_date(ymd_hms(now())) - 7) %>%
  summarize(cases_weekly_growth = round((max(cases) - min(cases)) / min(cases), 2), cases_weekly_per_mil = signif(((max(cases) - min(cases)) / mean(pop_2019) * 1000000 / 2), 3), wk_ending = max(as_of)) %>% 
  arrange(desc(cases_weekly_growth))
```
done



```{r echo=FALSE, message=FALSE, warning=FALSE}
test_growth %>%
  inner_join(code_names, by = "code") %>%
  inner_join(case_growth, by = "code") %>% 
  arrange(desc(tests_weekly_per_mil)) %>% 
  filter((tests_weekly_per_mil < quantile(test_growth$tests_weekly_per_mil, probs = 0.2, na.rm = TRUE))
         | (tests_weekly_per_mil > quantile(test_growth$tests_weekly_per_mil, probs = 0.8, na.rm = TRUE)) | code == "NJ") %>% 
  ggplot() +
  geom_col(mapping = aes(x = reorder(x = code, X = tests_weekly_per_mil), y = tests_weekly_per_mil, fill = reg_2)) +
  labs(x = "state", y = "Weekly tests per million residents", title = stringr::str_c("States with the fewest and most tests per million"), subtitle = str_c("One week ending", death_growth$wk_ending[1], sep = " ")) +
  theme(legend.title=element_blank())
```


Tests & cases
```{r warning=FALSE}
my_data %>% 
  inner_join(code_names, by = "code") %>% 
  inner_join(st_pop_2019, by = "name") %>%
  filter(as_of >= Sys.Date() - days(7)) %>% 
  mutate(week_num = lubridate::week(as_of)) %>% 
  group_by(code) %>%
  summarize(pos_rate = sum(case_ch) / sum(test_ch), reg_2 = min(reg_2)) %>% 
  mutate(pos_rate = if_else(pos_rate < 0, 0, pos_rate)) %>% 
  filter(pos_rate < 0.05 | pos_rate > 0.10) %>% 
  ggplot(mapping = aes(x = reorder(code, pos_rate), y = pos_rate, fill = reg_2)) +
  geom_col() +
  geom_label(mapping = aes(label = code)) +
  labs(x = "Date", y = "Share of COVID-19 tests with positive results", title = "Positive rates remain high in the Midwest and plains", subtitle = str_c("Week ending  ", max(my_data$as_of))) +
  theme(legend.title = element_blank(), axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank())
```

Tests & cases
```{r warning=FALSE}
my_data %>% 
  inner_join(code_names, by = "code") %>% 
  inner_join(st_pop_2019, by = "name") %>%
  filter(as_of >= Sys.Date() - days(7)) %>% 
  mutate(case_days = if_else(between(as_of, Sys.Date() - days(6), Sys.Date() - days(6)), 1, 0),
         death_days = if_else(as_of >= Sys.Date() - days(6), 1, 0)) %>% 
  group_by(code) %>%
  summarize(cfr = sum(death_ch * death_days) / sum(case_ch * case_days), reg_2 = min(reg_2)) %>% 
  ggplot(mapping = aes(x = reorder(code, cfr), y = cfr, fill = reg_2)) +
  geom_col() +
  geom_label(mapping = aes(label = code)) +
  labs(x = "Date", y = "Deaths as a share of confirmed cases", title = "Case fatality rate") +
  theme(legend.title = element_blank(), axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank())
```




Tests & cases
```{r warning=FALSE}
my_data %>% 
  inner_join(code_names, by = "code") %>% 
  inner_join(st_pop_2019, by = "name") %>%
  filter(as_of >= Sys.Date() - weeks(4)) %>% 
  mutate(week_num = lubridate::week(as_of)) %>% 
  group_by(week_num, reg_2) %>%
  summarize(as_of = median(as_of), pos_rate = sum(case_ch) / sum(test_ch)) %>% 
  ggplot(mapping = aes(x = as_of, y = pos_rate, color = reg_2, fill = reg_2)) +
  geom_smooth(alpha = .05, span = .5) +
  labs(x = "Date", y = "Share of COVID-19 tests with positive results", title = "Positive rates are trending upward", subtitle = str_c("Month ending  ", max(my_data$as_of))) +
  theme(legend.title = element_blank())
```


Tests & cases
```{r warning=FALSE}
my_data %>% 
  inner_join(code_names, by = "code") %>% 
  inner_join(st_pop_2019, by = "name") %>%
  filter(as_of >= Sys.Date() - months(1)) %>% 
  mutate(week_num = lubridate::week(as_of)) %>% 
  group_by(week_num, reg_2) %>%
  summarize(as_of = median(as_of), pos_rate = sum(case_ch) / sum(test_ch), wk_test = sum(test_ch)) %>% 
  ggplot(mapping = aes(x = as_of, y = pos_rate, color = reg_2, fill = reg_2)) +
  geom_smooth(span = .5) +
  geom_line() +
  labs(x = "Date", y = "Share of COVID-19 tests with positive results", title = "Positive rates remain high in the plains and midwest", subtitle = str_c("Two months ending  ", max(my_data$as_of))) +
  theme(legend.title = element_blank())
```



Tests & cases
```{r warning=FALSE}
my_data %>% 
  inner_join(code_names, by = "code") %>% 
  inner_join(st_pop_2019, by = "name") %>%
  filter(as_of >= Sys.Date() - months(1)) %>% 
  mutate(week_num = lubridate::week(as_of)) %>% 
  group_by(week_num, code) %>%
  summarize(pos_rate = sum(case_ch) / sum(test_ch),
            as_of = median(as_of),
            reg_2 = mode(reg_2)) %>% 
  group_by(code, week_num) %>% 
  mutate(y_label = if_else(as_of == median(as_of, na.rm = TRUE),
                           median(pos_rate, na.rm = TRUE),
                           NULL),
         month_pos = mean(pos_rate, na.rm = TRUE)) %>% 
  ungroup() %>% 
  ggplot(mapping = aes(x = as_of, y = pos_rate)) +
  geom_line(alpha = 0, span = .6, mapping = aes(color = reg_2)) +
  geom_label(mapping = aes(y = y_label, label = code), na.rm = TRUE) +
  labs(x = "Date", y = "Share of COVID-19 tests with positive results", title = "Positive rates remain high in some states", subtitle = str_c(Sys.Date() - months(1), " through ", max(my_data$as_of), "; Ordered by highest positive rate for the month"))
# +
#   theme(legend.title = element_blank()) +
#  facet_wrap(facets = vars(reorder(code, desc(month_pos))), nrow = 5) +
#    theme(axis.text = element_blank(),
#        axis.ticks = element_blank(),
#  axis.title.x  = element_blank(),
# strip.text.x = element_blank(),
# legend.position = 0)
```






```{r echo=FALSE}
test_growth %>%
  inner_join(code_names, by = "code") %>%
  inner_join(death_growth, by = "code") %>% 
  arrange(desc(tests_weekly_per_mil)) %>% 
  # filter(tests_weekly_per_mil < quantile(test_growth$tests_weekly_per_mil, probs = 0.5)) %>% 
  ggplot(mapping = aes(x = death_weekly_growth, y = tests_weekly_per_mil, label = code, fill = reg_2), na.rm = TRUE) +
  geom_label_repel() +
  labs(x = "Growth in weekly deaths", y = "Weekly tests per million residents", title = stringr::str_c("State tests and weekly growth in deaths"), subtitle = str_c("2 weeks ending", death_growth$wk_ending[1], sep = " ")) +
  theme(legend.title=element_blank())
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

case_growth %>%
  inner_join(code_names) %>% 
  inner_join(my_data) %>% 
  arrange(desc(cases_weekly_per_mil)) %>% 
  filter((cases_weekly_per_mil > quantile(case_growth$cases_weekly_per_mil, probs = 0.8, na.rm = TRUE) |
           cases_weekly_per_mil < quantile(case_growth$cases_weekly_per_mil, probs = 0.2, na.rm = TRUE) |
           code %in% c("CA", "TX", "FL", "NJ")) & (code != "HI")) %>% 
  group_by(code) %>% 
  filter(as_of >= today() - days(13) ) %>% 
  mutate(pos_rate = sum(case_ch) / sum(test_ch)) %>% 
  ungroup() %>% 
  ggplot(mapping = aes(x = reorder(code, X = desc(cases_weekly_per_mil)), y = cases_weekly_per_mil)) +
  geom_col(mapping = aes(fill = pos_rate)) +
  labs(x = "state",
       y = "Weekly cases per million residents",
       title = stringr::str_c("States with most or least new cases per million"),
       subtitle = str_c("Week ending", case_growth$wk_ending[1], sep = " "), fill = "pos. rate",
       caption = "lighter colors indicate higher positive rate"
       ) +
  theme_fivethirtyeight() +
  theme(legend.position = "none")

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
death_growth %>%
  inner_join(code_names) %>% 
  arrange(desc(death_weekly_per_mil)) %>% 
  filter(death_weekly_per_mil > quantile(death_growth$death_weekly_per_mil, probs = 0.8, na.rm = TRUE) |
           death_weekly_per_mil < quantile(death_growth$death_weekly_per_mil, probs = 0.2, na.rm = TRUE) |
           code %in% c("CA", "FL", "TX", "NJ")) %>% 
  inner_join(my_data) %>%
  group_by(code) %>% 
  filter(as_of >= today() - days(6) ) %>% 
  mutate(cfr = sum(death_ch) / sum(case_ch)) %>% 
  ungroup() %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(code, X = desc(death_weekly_per_mil)), y = death_weekly_per_mil, fill = cfr)) +
  labs(x = "state", y = "Weekly deaths per million residents", title = stringr::str_c("States with most & fewest deaths per million"), subtitle = str_c("Week ending", case_growth$wk_ending[1], sep = " ")) +
  theme(legend.title=element_blank())
```




```{r echo=FALSE, message=FALSE, warning=FALSE}


my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  group_by(reg_2) %>% 
  filter(as_of > Sys.Date() - months(1)) %>%
  # wday(as_of) == wday(max(as_of)),
  ungroup() %>% 
  group_by(reg_2, as_of) %>% 
  summarize(case_sum = sum(case_ch) / sum(pop_2019) * 1000000) %>%
  ggplot() +
  geom_smooth(mapping = aes(x = as_of, y = case_sum, color = reg_2, fill = reg_2), alpha = .1) +
  labs(x = "Date", y = "New cases per million", title = "New cases drop sharply in the northeast while the south rises again", subtitle = str_c("Month ending ", case_growth$wk_ending[1])) +
  theme(legend.title=element_blank())
```


Adds 2016 presidential election results
```{r}
results_2016 <- read_csv("results_2016.csv")
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  filter(between(as_of, ymd(20200601), ymd(20200630))) %>% 
  group_by(code) %>% 
  mutate(case_growth = 100 * (cases - min(cases, na.rm = TRUE))/ min(cases, na.rm = TRUE),
         is_clinton = (t_mgn < 0),
         month_growth = max(case_growth, na.rm = TRUE)) %>%
  ungroup() %>% 
  ggplot() +
  geom_smooth(mapping = aes(x = as_of, y = case_growth, color = is_clinton), na.rm = TRUE, span = .07) +
  labs(x = "state", y = "Growth rate of COVID-19 cases", title = "Sun belt states saw the highest COVID-19 case growth rates in June", subtitle = "Growth rate of total COVID-19 cases from 1 to 30 June 2020 by state") +
  facet_wrap(facets = vars(reorder(code, desc(month_growth))), nrow = 5) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x  = element_blank(),
        strip.background = element_rect(fill = "lightgray"),
        legend.position = 0)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
max_ch <- merge(my_data, merge(st_pop_2019, code_names, all = FALSE), all = FALSE)[between(as_of, ymd(20200601), ymd(20200630)), c("case_ch", "pop_2019", "code", "as_of")] %>%
  .[,"case_ch_per_mil" := round(case_ch / pop_2019 * 1E6)] %>% 
  .[case_ch_per_mil == max(case_ch_per_mil),]

my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  filter(between(as_of, ymd(20200601), ymd(20200630))) %>% 
  group_by(code) %>% 
  mutate(month_ch = (max(cases, na.rm = TRUE) - min(cases, na.rm = TRUE)) / pop_2019,
         is_clinton = (t_mgn < 0),
         case_sum = case_ch / pop_2019 * 1000000,
         y_label = if_else(lubridate::mday(as_of) == 7, case_sum + 50, NULL)) %>%
  ungroup() %>% 
  ggplot() +
  geom_smooth(mapping = aes(x = as_of, y = case_sum, color = is_clinton, fill = is_clinton), alpha = .1, na.rm = TRUE, span = .4) +
  geom_label(mapping = aes(x = as_of, y = y_label, label = code, color = is_clinton), na.rm = TRUE) +
  labs(x = "state", y = "New daily COVID-19 cases per million residents", title = "Sun belt states saw the most new COVID-19 cases in June", subtitle = "Data from 1 to 30 June 2020 by state in order of total new June cases", caption = str_c("Max new cases per million on one day was ", max_ch[,case_ch_per_mil], " on ", max_ch$as_of[1], " in ", max_ch[, "code"], ". Multiple states reported 0 new cases on various days")) +
  facet_wrap(facets = vars(reorder(code, desc(month_ch))), nrow = 7) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x  = element_blank(),
        strip.text.x = element_blank(),
        legend.position = 0)
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  group_by(reg_2) %>% 
  # filter(code %in% c("AZ", "FL", "SC", "AL", "MS", "CA", "MN", "NY", "GA", "TX")) %>% 
  filter(as_of > Sys.Date() - months(1)
         # ,reg_2 %in% c("Northeast", "South", "Southwest")
         ) %>%
  # wday(as_of) == wday(max(as_of)),
  ungroup() %>% 
  group_by(code, as_of) %>% 
  summarize(case_sum = sum(case_ch) / sum(pop_2019) * 1000000, reg_2 = min(reg_2)) %>%  
  mutate(reg_2 = factor(reg_2, levels = c("Middle South", "Midwest", "Northeast", "Plain and Mountain", "South", "Southwest", "West Coast"))) %>% 
  ggplot() +
  geom_smooth(mapping = aes(x = as_of, y = case_sum, color = reg_2), alpha = .1) +
  labs(x = "state", y = "New cases per million", title = "Do the appearance of new cases align with protests?", subtitle = str_c("Data from the month ending ", case_growth$wk_ending[1], " could offer clues", sep = " "))
# +
#  facet_wrap(facets = vars(reorder(code, reg_2)), nrow = 5) +
#  theme(axis.text = element_blank(),
#        axis.ticks = element_blank(),
#        axis.title.x  = element_blank(),
#        strip.background = element_rect(fill = "lightgray"),
#        legend.title = element_blank())
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
case_growth %>%
  inner_join(my_data) %>%
  inner_join(code_names) %>% 
  filter(as_of > today() - days(14)) %>% 
  arrange(desc(cases_weekly_growth)) %>% 
  group_by(code) %>% 
  mutate(pos_rate = sum(case_ch) / sum(test_ch)) %>% 
  ungroup() %>% 
  filter(cases_weekly_growth > quantile(case_growth$cases_weekly_growth, probs = 0.7, na.rm = TRUE)) %>% 
  ggplot() +
  geom_col(mapping = aes(x = reorder(code, X = desc(cases_weekly_growth)), y = cases_weekly_growth, color = reg_2, fill = pos_rate)) +
  labs(x = "state", y = "weekly case growth rate", title = stringr::str_c("Highest case growth rate by state, week ending", case_growth$wk_ending[1], sep = " ")) +
  theme(legend.title=element_blank())
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
death_growth %>%
  inner_join(code_names) %>% 
  ggplot(mapping = aes(x = death_weekly_growth, y = death_weekly_per_mil, color = reg_2)) +
  ## geom_point() +
  ggrepel::geom_text_repel(mapping = aes(label = code)) +
  labs(x = "Weekly death growth rate", y = "Weekly deaths per million", title = "Deaths over the past week per million and growth in deaths",
       subtitle = str_c("States face hard times"), case_growth$wk_ending[1]) +
  theme(legend.title=element_blank())
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
case_growth %>%
  inner_join(code_names) %>% 
  ggplot(mapping = aes(x = cases_weekly_growth, y = cases_weekly_per_mil, color = reg_2)) +
  ## geom_point() +
  ggrepel::geom_text_repel(mapping = aes(label = code)) +
  labs(x = "Weekly case growth rate", y = "Weekly new cases per million", title = "Cases over the past week per million and growth in cases",
       subtitle = "Shows states having a hard time now and those who may face hard times soon") +
  theme(legend.title=element_blank())
```



```{r echo=FALSE, message=FALSE, warning=FALSE}

my_data %>% 
  filter(as_of >= ymd(20200616)) %>% 
  group_by(as_of) %>%
  summarize(us_cases = sum(cases, na.rm = TRUE),
            us_cases_ch = sum(case_ch, na.rm = TRUE),
            us_deaths = sum(death, na.rm = TRUE),
            us_deaths_ch = sum(death_ch, na.rm = TRUE)) %>% 
  mutate(since = min(as_of),
         casesch_a = if_else(as_of <= ymd(20200716), us_cases_ch, NULL),
         casesch_b = if_else(as_of >= ymd(20200716) & as_of <= ymd(20200901), us_cases_ch, NULL),
         casesch_c = if_else(as_of >= ymd(20200901), us_cases_ch, NULL)) %>% 
  ggplot(mapping = aes(x = as_of)) +
  
  geom_smooth(mapping = aes(y = casesch_a, color = weekdays(as_of)), na.rm = TRUE, method = 'lm', linetype = 'dotted', alpha = 0) +
  geom_smooth(mapping = aes(y = casesch_b, color = weekdays(as_of)), na.rm = TRUE, method = 'lm', linetype = 'dotted', alpha = 0) +
  geom_smooth(mapping = aes(y = casesch_c, color = weekdays(as_of)), na.rm = TRUE, method = 'lm', linetype = 'dotted', alpha = 0) +
  
  geom_smooth(mapping = aes(y = casesch_a), na.rm = TRUE, method = 'lm', linetype = 'dotted', alpha = 0.5) +
  geom_smooth(mapping = aes(y = casesch_b), na.rm = TRUE, method = 'lm', linetype = 'dotted', alpha = 0.5) +
  geom_smooth(mapping = aes(y = casesch_c), na.rm = TRUE, method = 'lm', linetype = 'dotted', alpha = 0.5) +
  
  geom_point(mapping = aes(y = us_cases_ch), na.rm = TRUE) +
  geom_vline(xintercept = ymd(20200716), linetype = 'dashed') +
  theme(legend.position = "none") +
  labs(title = "Did case growth change when HHS took over reporting from CDC on 16 July?", subtitle = "New U.S. cases per day since 1 July using state data", x = NULL, y = "COVID-19 daily cases") +
  ylim(0, 80000)
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
pk <- c("AZ")


my_data %>% 
  filter(code %in% pk) %>%
    mutate(death_ch = if_else(as_of == ymd("2020-04-30") & code == pk, 50, as.double(death_ch))) %>% 
  group_by(as_of) %>%
  summarize(us_cases = sum(cases, na.rm = TRUE),
            us_cases_ch = sum(case_ch, na.rm = TRUE),
            us_deaths = sum(death, na.rm = TRUE),
            us_deaths_ch = sum(death_ch, na.rm = TRUE)) %>% 
  filter(us_deaths > 9) %>% 
  mutate(since = min(as_of),
         is_day = if_else(weekdays(as_of) == weekdays(my_data[[1,1]]), 0.3, 0.1)) %>% 
  ggplot(mapping = aes(x = as_of, y = us_deaths_ch)) +
  geom_smooth(linetype = 0, mapping = aes(fill = weekdays(as_of), alpha = is_day)) +
  geom_smooth(size = 1, alpha = 0, linetype = 2, color = "black") +
  geom_vline(xintercept = ymd(20200526) + days(5)) +
  theme(legend.position = "none") +
  labs(title = str_c("Are", pk, "deaths plateauing or even dropping?", sep = " "), subtitle = str_c("Deaths per day since", min(my_data[code %in% pk, as_of]), sep = " "), x = NULL, y = "COVID-19 daily deaths") +
  scale_alpha(range = c(.1, .3))
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
pk <- c("OK")


my_data %>% 
  filter(code %in% pk) %>%
  mutate(case_ch = as.double(case_ch)) %>%
  group_by(as_of) %>%
  summarize(us_cases = sum(cases, na.rm = TRUE),
            us_cases_ch = sum(case_ch, na.rm = TRUE),
            us_deaths = sum(death, na.rm = TRUE),
            us_deaths_ch = sum(death_ch, na.rm = TRUE)) %>% 
  filter(us_deaths > 9) %>% 
  mutate(since = min(as_of),
         is_day = if_else(weekdays(as_of) == weekdays(my_data[[1,1]]), 0.3, 0.1)) %>% 
  ggplot(mapping = aes(x = as_of, y = us_cases_ch)) +
  geom_smooth(linetype = 1, mapping = aes(fill = weekdays(as_of), color = weekdays(as_of))) +
  # geom_smooth(size = 1, alpha = 0, linetype = 1, color = "black", span = .5) +
  geom_vline(xintercept = ymd(20200621), color = "dodgerblue", linetype = 2) +
  theme(legend.title = element_blank()) +
  labs(title = str_c("It appears as though", pk, "cases are growing", sep = " "), subtitle = str_c("Cases per day since", min(my_data[death_ch > 9 & code == 'OK', as_of]), sep = " "), x = NULL, y = "New COVID-19 cases by day", caption = "The vertical, dashed blue line marks the President's 21 June rally in Tulsa") +
  scale_alpha(range = c(.1, .3))
```


```{r}
pk <- c("OK")


my_data %>% 
  filter(code %in% pk) %>%
  mutate(case_ch = as.double(case_ch)) %>%
  group_by(as_of) %>%
  summarize(us_cases = sum(cases, na.rm = TRUE),
            us_cases_ch = sum(case_ch, na.rm = TRUE),
            us_deaths = sum(death, na.rm = TRUE),
            us_deaths_ch = sum(death_ch, na.rm = TRUE)) %>% 
  filter(us_deaths > 9,
         weekdays(as_of) %in% c("Sunday", "Tuesday")) %>% 
  mutate(since = min(as_of),
         is_day = if_else(weekdays(as_of) == weekdays(my_data[[1,1]]), 0.3, 0.1)) %>% 
  ggplot(mapping = aes(x = as_of, y = us_cases_ch, color = weekdays(as_of))) +
  geom_smooth(alpha = 0, span = 0.3) +
  theme(legend.position = "none") +
  labs(title = "Two states whose paths diverged in November", subtitle = str_c("New cases of COVID-19 per day since", min(my_data[death_ch > 9 & code == 'OK', as_of]), sep = " "), x = NULL, y = "New daily cases", caption = "Just kidding. The orange line connects Oklahoma case numbers reported\non Sundays and the blue is Oklahoma case numbers from Tuesdays") +
  scale_color_manual(values = c("orange", "blue"))
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
pk <- c("")

my_data %>% 
  # filter(code %in% pk) %>%
  group_by(as_of, code) %>%
  summarize(us_cases = sum(cases, na.rm = TRUE),
            us_cases_ch = sum(case_ch, na.rm = TRUE),
            us_deaths = sum(death, na.rm = TRUE),
            us_deaths_ch = sum(death_ch, na.rm = TRUE)) %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  filter(as_of > ymd(20200331)) %>%
  # filter(reg_2 %in% c("South", "Midwest", "Northeast", "Southwest")) %>% 
  ggplot(mapping = aes(x = as_of, y = us_cases_ch/pop_2019 * 1000000)) +
  # geom_smooth(linetype = 0, mapping = aes(fill = weekdays(as_of)), alpha = 0.1) +
  geom_smooth(size = 1, linetype = 1, mapping = aes(color = reg_2, fill = reg_2), span = .3, alpha = .1) +
  geom_vline(xintercept = ymd("2020-05-22") + days(5), color = "red", linetype = 2) +
  geom_vline(xintercept = ymd("2020-05-29") + days(5), color = "blue", linetype = 2) +
  theme(legend.title = element_blank()) +
  labs(title = "After mid-May, cases fell in the North from Minnesota to Maine\nand rose sharply in sun belt states from Arizona to Florida", x = NULL, y = "New COVID-19 cases per million residents", caption = "Vertical red and blue lines mark five days after the start of\nMemorial Day weekend and national protests, respectively", subtitle = str_c("Data as of ", max(my_data$as_of)))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
pk <- c("NY")

my_data %>% 
  filter(code != pk) %>% 
  group_by(as_of) %>%
  summarize(us_cases = sum(cases, na.rm = TRUE),
            us_cases_ch = sum(case_ch, na.rm = TRUE),
            us_deaths = sum(death, na.rm = TRUE),
            us_deaths_ch = sum(death_ch, na.rm = TRUE)) %>% 
  filter(us_cases > 99) %>%
  mutate(since = min(as_of)) %>% 
  ggplot(mapping = aes(x = as_of, y = us_deaths_ch)) +
  geom_smooth(linetype = "dashed", color = "black") +
  geom_smooth(linetype = 0, mapping = aes(fill = weekdays(as_of)), alpha = 0.1) +
  labs(title = str_c("Are non-", str_c(pk, collapse = ", "), " deaths plateauing or dropping?", sep = ""), subtitle = "U.S. deaths since the 100th case", x = "date", y = "COVID-19 deaths")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
pk <- c("NY", "NJ", "CT", "CA", "MI")


my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  mutate(noreast = if_else(code %in% (pk), "Northeastern states", "All other states")) %>% 
  group_by(noreast, as_of) %>%
  summarize(us_cases = sum(cases, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE),
            us_cases_ch = sum(case_ch, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE),
            us_deaths = sum(death, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE),
            us_deaths_ch = sum(death_ch, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE)) %>% 
  mutate(since = min(as_of),
         label_x = max(as_of, na.rm = TRUE),
         label_y = max(us_cases_ch, na.rm = TRUE)) %>% 
  ggplot(mapping = aes(x = as_of, y = us_cases, color = noreast)) +
  # geom_smooth(linetype = 0, alpha = .1, mapping = aes(fill = weekdays(as_of)), span = .05) +
  # geom_smooth(alpha = 0, size = 1, linetype = 2) +
  geom_line() +
  # theme(legend.position = "none") +
  
  labs(title = str_c("Since June, ", str_c(pk, collapse = ", "), " have had fewer cases", sep = ""), subtitle = "Cases per million residents split by group", x = "date", y = "COVID-19 new cases")
```

```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  mutate(noreast = if_else(code %in% (pk), "Northeastern states", "All other states")) %>% 
  group_by(noreast, as_of) %>%
  summarize(us_cases = sum(cases, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000,
            us_cases_ch = sum(case_ch, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000,
            us_deaths = sum(death, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000,
            us_deaths_ch = sum(death_ch, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000) %>% 
  # filter(us_cases > .00000009) %>%
  mutate(since = min(as_of)) %>% 
  ggplot(mapping = aes(x = as_of, y = us_deaths_ch)) +
  geom_smooth(linetype = 0, alpha = .0, mapping = aes(fill = weekdays(as_of), color = noreast), span = 0.8) +
  geom_smooth(alpha = 0, size = 1, linetype = 2, mapping = aes(color = noreast), span = 0.2) +
  # geom_smooth(color = "black") +
  theme(legend.position = "none") +
  labs(title = str_c(str_c(pk, collapse = ", "), " have switched w/others", sep = ""), x = "date", y = "COVID-19 deaths per million residents") +
  ylim(0,7.5)
```




```{r echo=FALSE, message=FALSE, warning=FALSE}
top_n(death_growth, n = 20) %>%
  inner_join(top_n(case_growth, n = 20)) %>%
  inner_join(code_names) %>% 
  filter((death_weekly_per_mil > as.numeric(reorder(death_growth$death_weekly_per_mil, desc(death_growth$death_weekly_per_mil))[[11]])) |
           (cases_weekly_per_mil > as.numeric(reorder(case_growth$cases_weekly_per_mil, desc(case_growth$cases_weekly_per_mil))[[11]]))) %>% 
  ggplot(mapping = aes(x = death_weekly_per_mil, y = cases_weekly_per_mil)) +
  geom_smooth(method = "lm", mapping = aes(color = NULL), linetype = "dotted", fill = 0.1, color = "lightgray") +
  ## geom_point(mapping = aes(color = reg_2), size = 2) +
  ggrepel::geom_text_repel(mapping = aes(label = code, color = reg_2)) +
  labs(x = "Weekly deaths per million", y = "Weekly new cases per million", title = "States dealing with a lot right now", subtitle = str_c("As of ", death_growth[[1, "wk_ending"]])) +
  theme(legend.title=element_blank())
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
death_growth %>%
  inner_join(case_growth) %>%
  inner_join(code_names) %>% 
  filter((death_weekly_growth > 0.03) |
           (cases_weekly_growth > 0.03)) %>%
  ggplot(mapping = aes(x = log(death_weekly_growth), y = log(cases_weekly_growth), color = reg_2)) +
  ggrepel::geom_text_repel(mapping = aes(label = code),
                           arrow = arrow(length = unit(x = 0.05, units = "npc"))) +
  labs(x = "Weekly growth in deaths", y = "Weekly growth in cases", title = "States where the growth of deaths or new cases are rising", subtitle = str_c("As of ", death_growth[[1, "wk_ending"]])) +
  theme(legend.title=element_blank())
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
death_growth %>%
  inner_join(case_growth) %>%
  inner_join(code_names) %>% 
  mutate(xmax = max(death_weekly_growth, na.rm = TRUE),
         ymax = max(cases_weekly_growth, na.rm = TRUE)) %>% 
  filter((death_weekly_growth <= 0.03) |
           (cases_weekly_growth <= 0.03)) %>% 
  ggplot(mapping = aes(x = death_weekly_growth, y = cases_weekly_growth, color = reg_2)) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_label_repel(mapping = aes(label = code, color = reg_2),
                       arrow = arrow(length = unit(x = 0.05, units = "npc"))) +
  labs(x = "Weekly growth in deaths", y = "Weekly growth in cases", title = "States where new deaths or cases are flat or falling", subtitle = str_c("Two weeks ending ", death_growth[[1, "wk_ending"]])) +
  theme(legend.title=element_blank()) 
```






```{r echo=FALSE, message=FALSE, warning=FALSE}
top_n(death_growth, n = 20) %>%
  inner_join(top_n(case_growth, n = 20)) %>%
  inner_join(code_names) %>% 
  filter((death_weekly_per_mil > as.numeric(reorder(death_growth$death_weekly_per_mil, desc(death_growth$death_weekly_per_mil))[[11]])) |
           (cases_weekly_per_mil > as.numeric(reorder(case_growth$cases_weekly_per_mil, desc(case_growth$cases_weekly_per_mil))[[11]]))) %>% 
  ggplot(mapping = aes(x = death_weekly_per_mil, y = cases_weekly_per_mil)) +
  geom_smooth(method = "lm", mapping = aes(color = NULL), linetype = "dotted", fill = 0.1, color = "lightgray") +
  ## geom_point(mapping = aes(color = reg_2), size = 2) +
  ggrepel::geom_text_repel(mapping = aes(label = code, color = reg_2)) +
  labs(x = "Weekly deaths per million", y = "Weekly new cases per million", title = "States dealing with a lot right now", subtitle = str_c("As of ", death_growth[[1, "wk_ending"]])) +
  theme(legend.title=element_blank())
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  filter(as_of == max(as_of)) %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  mutate(cases_pm = cases / pop_2019 * 1E6,
         deaths_pm = death / pop_2019 * 1E6) %>% 
  arrange(desc(deaths_pm)) %>% 
  top_n(15) %>%
  mutate(y_label = cases_pm, x_label = as_of) %>% 
  select(code, y_label, x_label) %>% 
  inner_join(my_data) %>% 
  arrange(code, as_of) %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  mutate(cases_pm = cases / pop_2019 * 1E6,
         deaths_pm = death / pop_2019 * 1E6,
         x_label = if_else(as_of == max(as_of), x_label, NULL)) %>%
  ggplot() +
  geom_line(mapping = aes(x = as_of, y = cases_pm, color = code)) +
  geom_label_repel(mapping = aes(x = x_label, y = y_label, label = code, color = code)) +
  
  theme(legend.position = "none")
  
  
  


  

```




```{r echo=FALSE, message=FALSE, warning=FALSE}
since_100 <- my_data %>% 
  arrange(code, as_of) %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  mutate(cases_pm = cases / pop_2019 * 1E6,
         deaths_pm = death / pop_2019 * 1E6) %>% 
  filter(cases_pm >= 100) %>% 
  group_by(code) %>% 
  mutate(days_in = as.integer(as_of - min(as_of))) %>% 
  ungroup()
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
since_100_labels <- since_100 %>% 
  group_by(code) %>% 
  summarize(lab_days = max(days_in), lab_deaths = max(deaths_pm))

test_code <- c("MN", "TX", "AZ", "CA", "FL", "OK", "MN", "NY", "NJ", "ND", "SD")

since_100 %>%
  filter(code %in% test_code) %>%
  inner_join(since_100_labels) %>%
  group_by(code) %>% 
  mutate(lab_days = if_else(lab_days == days_in, lab_days, NULL),
         lab_deaths = if_else(lab_deaths == deaths_pm, lab_deaths, NULL)) %>%
  ggplot(mapping = aes(color = code, x = days_in, y = deaths_pm)) +
  geom_line() +
  geom_label_repel(aes(x = lab_days, y = lab_deaths, label = code), na.rm = TRUE) +
  labs(x = "Days since a state identified COVID-19 in 0.01% of its residents",
       y = "Cumulative deaths per million residents",
       title = "Allows for comparison between states on different timelines") +
  theme(legend.title=element_blank())
  

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
since_100 %>%
  filter(as_of >= now() - weeks(2)) %>% 
  group_by(code) %>% 
  filter(deaths_pm > quantile(deaths_pm, probs = .8, na.rm = TRUE) | deaths_pm < quantile(deaths_pm, probs = .2, na.rm = TRUE)) %>% 
  arrange(desc(deaths_pm)) %>% 
  ggplot() +
  geom_col(mapping = aes(x = reorder(code, X = desc(deaths_pm)), y = deaths_pm, fill = reg_2)) +
  labs(x = "state", y = "Weekly deaths per million residents", title = stringr::str_c("States with most & fewest deaths per million"), subtitle = str_c("As of ", case_growth$wk_ending[1], sep = " ")) +
  theme(legend.title=element_blank(), axis.text.x = element_text(angle = 90, size = 8))
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
since_100_labels <- since_100 %>% 
  group_by(code) %>% 
  summarize(lab_days = max(days_in), lab_cases = max(cases_pm))

test_code <- c("MN", "TX", "AZ", "CA", "FL", "OK", "MN", "NY")

since_100 %>%
  filter(code %in% test_code) %>%
  inner_join(since_100_labels) %>%
  group_by(code) %>% 
  mutate(lab_days = if_else(lab_days == days_in, lab_days, NULL),
         lab_cases = if_else(lab_cases == cases_pm, lab_cases, NULL)) %>%
  ggplot(mapping = aes(color = code, x = days_in, y = cases_pm)) +
  geom_line() +
  geom_label_repel(aes(x = lab_days, y = lab_cases, label = code), na.rm = TRUE) +
  labs(x = "Days since a state identified COVID-19 in 0.01% of its residents",
       y = "Cumulative cases per million residents",
       title = "Allows for comparison between states on different timelines") +
  theme(legend.title=element_blank())
  

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
since_100 %>% 
  inner_join(since_100_labels) %>% 
  mutate(cfr = death / cases,
         tests_pm = tests / pop_2019 * 1E6) %>% 
  filter(days_in == 21) %>% 
  ggplot(mapping = aes(x = tests_pm, y = cfr, label = code)) +
  geom_smooth(method = "lm") +
  geom_text_repel(mapping = aes(color = reg_2)) +
  labs(x = "Coronavirus tests per million residents", y = "Case fatality ratio", title = "Testing more is associated with a lower case fatality rate") +
  theme(legend.title=element_blank())
  
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  filter(as_of > ymd(20200723)) %>% 
  group_by(code) %>% 
  mutate(new_cases = (max(cases, na.rm = TRUE) - min(cases, na.rm = TRUE)) / pop_2019 * 1000000,
         is_clinton = (median(t_mgn, na.rm = TRUE) < 0),
         case_ch_pm = case_ch / pop_2019 * 1000000,
         death_ch_pm = death_ch / pop_2019 * 1000000) %>% 
  ungroup() %>% 
  ggplot() +
  geom_smooth(mapping = aes(x = as_of, y = death_ch_pm, color = is_clinton), na.rm = TRUE, span = .3) +
  labs(x = "state", y = "New COVID-19 cases per million per day", title = "The Dakotas lead in deaths per capita since Sturgis", subtitle = "Total new COVID-19 cases per million from 24 August to today, by state") +
  facet_wrap(facets = vars(reorder(code, desc(new_cases))), nrow = 5) +
  theme_fivethirtyeight() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x  = element_blank(),
        strip.background = element_rect(fill = "lightgray"),
        legend.position = 0)
  
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
pk <- c("IA", "SD", "ND", "MN", "NE", "MT", "WY")

my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  mutate(sub_group = if_else(code %in% (pk), str_c(pk,collapse = ", "), "other states")) %>% 
  group_by(sub_group, as_of) %>%
  summarize(us_cases = sum(cases, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000,
            us_cases_ch = sum(case_ch, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000,
            us_deaths = sum(death, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000,
            us_deaths_ch = sum(death_ch, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000,
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE)) %>% 
  # filter(between(as_of, ymd(20200315), ymd(20200907))) %>% 
  mutate(since = min(as_of)) %>% 
  ggplot(mapping = aes(x = as_of, y = us_cases_ch, color = sub_group)) +
  geom_smooth(fill = "white", span = .2) +
  scale_color_fivethirtyeight("sub_group") +
  # geom_smooth(alpha = 0, size = 1) +
  geom_vline(xintercept = ymd(20200816), linetype = 2) +
  # geom_vline(xintercept = ymd(20200715), linetype = 2) +
  labs(title = str_c(str_c(pk, collapse = ", "), " infection rate has been higher since Aug", sep = ""), subtitle = "New daily cases per million residents, split by state", x = "date", y = "new daily COVID-19 cases per million residents", caption = "The Sturgis Motorcycle Rally is marked at 16 Aug") +
  ggthemes::theme_hc() +
  theme(legend.title = element_blank())
  
```


```{r}
pop_dens <- read_csv("pop_density.csv") %>% 
  select(code, dens = Density, pop = Pop)
```

```{r}
temp <- my_data %>%
  inner_join(pop_dens) %>% 
  filter(as_of == max(as_of, na.rm = TRUE)) %>% 
  mutate(death_pm = death / pop * 1E6,
         case_pm = cases / pop * 1E6,
         log_death_pm = log(death_pm, 10))
  
  

bestfit_intercept <- lm(formula = temp$log_death_pm ~ temp$dens)[[1]][[1]]
bestfit_slope <- lm(formula = temp$log_death_pm ~ temp$dens)[[1]][[2]]
```



```{r}
my_data %>% 
  inner_join(results_2016) %>%
  inner_join(pop_dens) %>%
  filter(as_of == max(as_of)) %>% 
  mutate(death_pm = death/pop * 1000000,
         log_death_pm = log(death_pm, base = 10)) %>%
  group_by(code) %>%
  mutate(hrc = (t_mgn < 0),
         tier = case_when(dens >= 485 ~ "F",
                          between(dens, 183, 485) ~ "E",
                          between(dens, 69, 183) ~ "D",
                          between(dens, 26, 69) ~ "C",
                          between(dens, 10, 26) ~ "B",
                          dens < 10 ~ "A")) %>% 
  ungroup() %>%
  ggplot(mapping = aes(x = dens, y = log_death_pm)) +
                       # , color = hrc, fill = hrc)) +
  geom_text_repel(mapping = aes(x = dens, y = log_death_pm, label = code, fill = NULL, color = hrc), position = position_jitter()) +
  # geom_smooth(linetype = 3, method = "lm", alpha = 0.1) +
  geom_abline(slope = bestfit_slope, intercept = bestfit_intercept, linetype = 3) +
  facet_wrap(vars(tier),  scales = "free_x", nrow = 2) +
  labs(x = "Population per square mile", y = "Log of COVID-19 deaths per million", title = "For many states, density is destiny", subtitle = str_c("States plotted by density and COVID-19 deaths along a best-fit line, as of ", case_growth$wk_ending[1])) +
  theme(legend.position = "none", strip.text = element_blank()) +
  ylim(0, 4)
  
```


```{r}
my_data %>% 
  inner_join(results_2016) %>%
  inner_join(pop_dens) %>%
  filter(as_of == max(as_of)) %>% 
  mutate(death_pm = death/pop * 1000000,
         log_death_pm = log(death_pm, base = 10),
         log_death_pm_model = bestfit_intercept + bestfit_slope * dens,
         death_pm_model = 10 ^ (log_death_pm_model),
         death_pm_res_pct  = (death_pm - death_pm_model) / death_pm_model * 100) %>% 
  ggplot(mapping = aes(x = reorder(code, desc(death_pm_res_pct)), y = death_pm_res_pct)) +
  geom_label(mapping = aes(label = code, color = dens, fill = desc(dens))) +
  # geom_smooth(linetype = 3, method = "lm", alpha = 0.1) +
  labs(x = NULL, y = "Log of COVID-19 deaths per million", title = "For many states, density is density", subtitle = str_c("States plotted by density and COVID-19 deaths along a best-fit line, as of ", case_growth$wk_ending[1])) +
  theme(legend.position = "none", strip.text = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank())


  
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(is_clinton = t_mgn < 0) %>% 
  group_by(as_of) %>%
  summarize(case_ch_pm = sum(case_ch) / sum(pop_2019) * 1000000,
            death_ch_pm = sum(death_ch) / sum(pop_2019) * 1000000,
            cases_pm = sum(cases) / sum(pop_2019) * 1000000,
            death_pm = sum(death) / sum(pop_2019) * 1000000) %>% 
  filter(cases_pm >= 10) %>% 
  ggplot(mapping = aes(x = as_of, y = case_ch_pm)) +
  geom_smooth(alpha = 0.2, na.rm = TRUE, span = 0.1) +
  labs(x = "Date", y = "Cumulative cases per million", title = "The U.S. is in its third wave", subtitle = "Daily COVID-19 cases per million residents") +
  theme(
    # axis.text = element_blank(),
    #     axis.ticks = element_blank(),
    #     axis.title.x  = element_blank(),
        # strip.background = element_rect(fill = "lightgray"),
        legend.position = 0)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(is_clinton = t_mgn < 0) %>% 
  group_by(is_clinton, as_of) %>%
  summarize(case_ch_pm = sum(case_ch) / sum(pop_2019) * 1000000,
            death_ch_pm = sum(death_ch) / sum(pop_2019) * 1000000,
            cases_pm = sum(cases) / sum(pop_2019) * 1000000,
            death_pm = sum(death) / sum(pop_2019) * 1000000) %>% 
  filter(cases_pm >= 10) %>% 
  ggplot() +
  geom_smooth(mapping = aes(x = as_of, y = case_ch_pm, color = is_clinton, fill = is_clinton), alpha = 0.1, na.rm = TRUE, span = .1) +
  labs(x = "Date", y = "New cases per day per million", title = "States Trump won have had more COVID-19 cases per capita since June", subtitle = "Daily COVID-19 cases per million residents by state's 2016 winner") +
  theme(
    # axis.text = element_blank(),
    #     axis.ticks = element_blank(),
    #     axis.title.x  = element_blank(),
        # strip.background = element_rect(fill = "lightgray"),
        legend.position = 0)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(is_clinton = t_mgn < 0) %>% 
  group_by(is_clinton, as_of) %>%
  summarize(case_ch_pm = sum(case_ch) / sum(pop_2019) * 1000000,
            death_ch_pm = sum(death_ch) / sum(pop_2019) * 1000000,
            cases_pm = sum(cases) / sum(pop_2019) * 1000000,
            death_pm = sum(death) / sum(pop_2019) * 1000000) %>% 
  filter(cases_pm >= 10) %>% 
  ggplot() +
  geom_smooth(mapping = aes(x = as_of, y = death_ch_pm, color = is_clinton, fill = is_clinton), alpha = 0.1, na.rm = TRUE, span = .1) +
  labs(x = "Date", y = "COVID-19 deaths per million per day", title = "States Trump won have had higher daily COVID-19 deaths since July", subtitle = "Total COVID-19 deaths per million per day by 2016 result") +
  theme(
    # axis.text = element_blank(),
    #     axis.ticks = element_blank(),
    #     axis.title.x  = element_blank(),
        # strip.background = element_rect(fill = "lightgray"),
        legend.position = 0)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(is_clinton = t_mgn < 0) %>% 
  group_by(is_clinton, as_of) %>%
  summarize(case_ch_pm = sum(case_ch) / sum(pop_2019) * 1000000,
            death_ch_pm = sum(death_ch) / sum(pop_2019) * 1000000,
            cases_pm = sum(cases) / sum(pop_2019) * 1000000,
            death_pm = sum(death) / sum(pop_2019) * 1000000,
            ) %>% 
  filter(cases_pm >= 10) %>% 
  ggplot() +
  geom_smooth(mapping = aes(x = as_of, y = cases_pm, color = is_clinton, fill = is_clinton), alpha = 0.1, na.rm = TRUE, span = .1) +
  labs(x = "Date", y = "Cumulative cases per day per million", title = "States Trump won have had more COVID-19 cases per capita since June", subtitle = "Total COVID-19 cases per million residents") +
  theme(
    # axis.text = element_blank(),
    #     axis.ticks = element_blank(),
    #     axis.title.x  = element_blank(),
        # strip.background = element_rect(fill = "lightgray"),
        legend.position = 0)
```






```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(is_clinton = t_mgn < 0) %>% 
  group_by(is_clinton, as_of) %>%
  summarize(case_ch_pm = sum(case_ch) / sum(pop_2019) * 1000000,
            death_ch_pm = sum(death_ch) / sum(pop_2019) * 1000000,
            cases_pm = sum(cases) / sum(pop_2019) * 1000000,
            death_pm = sum(death) / sum(pop_2019) * 1000000) %>% 
  filter(cases_pm >= 10) %>% 
  ggplot() +
  geom_smooth(mapping = aes(x = as_of, y = cases_pm, color = is_clinton, fill = is_clinton), alpha = 0.1, na.rm = TRUE, span = .1) +
  labs(x = "Date", y = "Cumulative cases per million", title = "States Trump won have had more total cases per capita since June", subtitle = "Daily COVID-19 cases per million residents") +
  theme(
    # axis.text = element_blank(),
    #     axis.ticks = element_blank(),
    #     axis.title.x  = element_blank(),
        # strip.background = element_rect(fill = "lightgray"),
        legend.position = 0)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(is_clinton = t_mgn < 0) %>% 
  group_by(is_clinton, as_of) %>%
  summarize(case_ch_pm = sum(case_ch) / sum(pop_2019) * 1000000,
            death_ch_pm = sum(death_ch) / sum(pop_2019) * 1000000,
            cases_pm = sum(cases) / sum(pop_2019) * 1000000,
            death_pm = sum(death) / sum(pop_2019) * 1000000) %>% 
  group_by(as_of) %>% 
  mutate(multy = 2 * is_clinton - 1,
         case_ch_pm_diff = if_else(sum(multy * case_ch_pm) < 0, - sum(multy * case_ch_pm) / 2, 0),
         death_ch_pm_diff = sum(multy * death_ch_pm),
         cases_pm_diff = sum(multy * cases_pm),
         death_pm_diff = if_else(sum(multy * death_pm) > 0, sum(multy * death_pm) / 2, 0)) %>% 
  ungroup() %>% 
  filter(cases_pm >= 10) %>% 
  ggplot(mapping = aes(x = as_of)) +
  geom_smooth(mapping = aes(x = as_of, y = death_pm, color = is_clinton, fill = is_clinton), alpha = 0.1, na.rm = TRUE, span = .1) +
  geom_point(mapping = aes(y = death_pm_diff), size = 1) +
  labs(x = "Date", y = "Cumulative COVID-19 deaths per million", title = "The gap in total deaths has been shrinking since July", subtitle = "Total COVID-19 deaths per million per day by 2016 result") +
  theme(
    # axis.text = element_blank(),
    #     axis.ticks = element_blank(),
    #     axis.title.x  = element_blank(),
        # strip.background = element_rect(fill = "lightgray"),
        legend.position = 0)
```


```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(results_2016) %>% 
  mutate(day_of_week = weekdays(as_of)) %>% 
  group_by(code, day_of_week) %>%
  mutate(max_case_ch = max(case_ch),
         hi_date = if_else(case_ch == max_case_ch, as_of, NULL),
         case_ch_pm = as.integer(case_ch / pop_2019 * 1000000),
         pos_rate = case_ch / test_ch) %>% 
  filter(hi_date == max(as_of)) %>% 
  select(as_of, code, case_ch_pm, pos_rate) %>% 
  arrange(desc(case_ch_pm)) %>% 
  group_by(code) %>% 
  summarize(as_of = max(as_of), case_ch_pm = mean(case_ch_pm, na.rm = TRUE), pos_rate = max(pos_rate, na.rm = TRUE)) %>% 
  ggplot(mapping = aes(x = reorder(code, desc(case_ch_pm)), y = case_ch_pm, fill = pos_rate)) +
  labs(title = str_c("States with a record number of new cases week ending ", max(my_data$as_of)),
       y = "Daily new cases per million",
       x = "State") +
  geom_col() +
  geom_label(mapping = aes(label = weekdays(as_of, abbreviate = TRUE)), color = "white") +
  theme(axis.text.x = element_text(angle = 90, size = 8))

```


```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(results_2016) %>% 
  mutate(day_of_week = weekdays(as_of)) %>% 
  group_by(code, day_of_week) %>%
  mutate(max_case_ch = max(case_ch),
         hi_date = if_else(case_ch == max_case_ch, as_of, NULL),
         case_ch_pm = as.integer(case_ch / pop_2019 * 1000000),
         pos_rate = case_ch / test_ch,
         is_hrc = (t_mgn < 0)) %>% 
  filter(hi_date == max(as_of)) %>% 
  select(as_of, code, case_ch_pm, pos_rate, is_hrc) %>% 
  arrange(desc(case_ch_pm)) %>% 
  group_by(code, is_hrc) %>% 
  summarize(as_of = max(as_of),
            case_ch_pm = mean(case_ch_pm, na.rm = TRUE),
            pos_rate = max(pos_rate, na.rm = TRUE)) %>% 
  ggplot(mapping = aes(x = reorder(code, desc(case_ch_pm)), y = case_ch_pm, fill = is_hrc)) +
  labs(title = str_c("States with a record number of new cases week ending ", max(my_data$as_of)),
       y = "Daily new cases per million",
       x = "State") +
  geom_col(color = "white") +
  geom_text(mapping = aes(label = weekdays(as_of, abbreviate = TRUE)), color = "black", angle = 90) +
  theme(axis.text.x = element_text(angle = 90, size = 8))

```


```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(results_2016) %>% 
  mutate(day_of_week = weekdays(as_of)) %>% 
  group_by(code, day_of_week, t_mgn) %>%
  mutate(max_case_ch = max(case_ch),
         hi_date = if_else(case_ch == max_case_ch, as_of, NULL),
         case_ch_pm = as.integer(case_ch / pop_2019 * 1000000),
         pos_rate = case_ch / test_ch,
         is_hrc = (t_mgn < 0)) %>% 
  filter(hi_date == max(as_of)) %>% 
  select(as_of, code, case_ch_pm, pos_rate, is_hrc) %>% 
  arrange(desc(case_ch_pm)) %>% 
  group_by(code, is_hrc) %>% 
  summarize(as_of = max(as_of), case_ch_pm = mean(case_ch_pm, na.rm = TRUE), pos_rate = max(pos_rate, na.rm = TRUE)) %>% 
  ggplot(mapping = aes(x = reorder(code, desc(case_ch_pm)), y = case_ch_pm, fill = pos_rate)) +
  labs(title = str_c("45 states had a record high number of new cases this week"),
       subtitle = str_c("week ending ", max(my_data$as_of)),
       y = "Daily new cases per million",
       x = "State") +
  geom_col() +
  geom_label(mapping = aes(label = weekdays(as_of, abbreviate = TRUE)), color = "white") +
  theme(axis.text.x = element_text(angle = 90, size = 8))

```


```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(results_2016) %>% 
  mutate(day_of_week = weekdays(as_of)) %>% 
  group_by(code, day_of_week) %>%
  mutate(max_death_ch = max(death_ch),
         hi_date = if_else(death_ch == max_death_ch, as_of, NULL),
         death_ch_pm = as.integer(death_ch / pop_2019 * 1000000),
         cfr = death_ch / case_ch,
         is_hrc = (t_mgn < 0)) %>% 
  filter(hi_date == max(as_of)) %>% 
  select(as_of, code, death_ch_pm, cfr, is_hrc) %>% 
  arrange(desc(death_ch_pm)) %>% 
  group_by(code, is_hrc) %>% 
  summarize(as_of = max(as_of), death_ch_pm = mean(death_ch_pm, na.rm = TRUE), cfr = max(cfr, na.rm = TRUE)) %>% 
  ggplot(mapping = aes(x = reorder(code, desc(death_ch_pm)), y = death_ch_pm, fill = is_hrc)) +
  labs(title = str_c("States with a record number of deaths week ending ", max(my_data$as_of)),
       y = "Daily deaths per million",
       x = "State") +
  geom_col() +
  geom_label(mapping = aes(label = weekdays(as_of, abbreviate = TRUE)), color = "white")
```



```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(year_mo = month(as_of)) %>% 
  group_by(year_mo, code) %>% 
  summarize(case_ch_pm = 30.5 * mean(case_ch / pop_2019 * 1000000, na.rm = TRUE),
            death_ch_pm = 30.5 * mean(death_ch / pop_2019 * 1000000, na.rm = TRUE),
            is_hrc = sum(t_mgn, na.rm = TRUE) < 0,
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            mo_of = median(ymd(str_c("2020", year_mo, "15", sep = "-")))) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  group_by(year_mo) %>% 
  top_n(n = 10, case_ch_pm) %>%
  ggplot(mapping = aes(x = mo_of, y = case_ch_pm, label = code, color = is_hrc, size = pos_rate)) +
  geom_label(direction = "y", segment.color = NA, position = position_jitter(width = 10, height = 60)) +
  theme(legend.position = "none") +
  scale_size(range = c(3, 6)) +
  labs(x = "month",
       y = "monthly cases per million",
       title = "Since June, red states have led in new cases per capita")

```


```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(year_mo = month(as_of)) %>% 
  group_by(year_mo, reg_2, code) %>% 
  summarize(case_ch_pm = 30.5 * mean(case_ch / pop_2019 * 1000000, na.rm = TRUE),
            death_ch_pm = 30.5 * mean(death_ch / pop_2019 * 1000000, na.rm = TRUE),
            is_hrc = sum(t_mgn, na.rm = TRUE) < 0,
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            mo_of = median(ymd(str_c("2020", year_mo, "15", sep = "-")))) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  group_by(year_mo) %>% 
  top_n(n = 10, case_ch_pm) %>%
  ggplot(mapping = aes(x = mo_of, y = case_ch_pm, label = code, fill = reg_2)) +
  geom_label(direction = "y", segment.color = NA, position = position_jitter(width = 10, height = 60)) +
  scale_size(range = c(3, 6)) +
  theme(legend.title = element_blank()) +
  labs(x = "month",
       y = "monthly cases per million",
       title = "Since June, red states have led in new cases per capita")

```



```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>%
  inner_join(pop_dens) %>%  
  mutate(year_wk = str_c(year(as_of),  week(as_of), sep = "-")) %>% 
  group_by(year_wk, code, dens) %>% 
  summarize(case_ch_pm = 7 * mean(case_ch / pop_2019 * 1000000, na.rm = TRUE),
            death_ch_pm = 7 * mean(death_ch / pop_2019 * 1000000, na.rm = TRUE),
            margin_2016 = mean(t_mgn, na.rm = TRUE),
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            wk_date = min(as_of, na.rm = TRUE)) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  group_by(wk_date) %>% 
  top_n(n = 3, death_ch_pm) %>%
  ggplot(mapping = aes(x = wk_date, y = death_ch_pm, label = code, fill = dens)) +
  geom_label(position = position_jitter(width = 10, height = 60), segment.color = NA) +
  labs(title = "Less dense states have led death rates since late June",
       subtitle = str_c("Three states with most per capita COVID-19 deaths by week through ", max(my_data[,as_of])),
       y = "Weekly COVID-19 deaths per million residents",
       x = NULL,
       fill = "pop. per\nsq. mi.") +
  scale_fill_gradient2(low = "dodgerblue", aesthetics = "fill", high = "orange" , midpoint = 300)



```




```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(year_wk = week(as_of)) %>% 
  group_by(year_wk, code) %>% 
  summarize(case_ch_pm = 7 * mean(case_ch / pop_2019 * 1000000, na.rm = TRUE),
            death_ch_pm = 7 * mean(death_ch / pop_2019 * 1000000, na.rm = TRUE),
            margin_2016 = mean(t_mgn, na.rm = TRUE),
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            wk_date = min(as_of, na.rm = TRUE)) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  group_by(wk_date) %>% 
  mutate(nat_death = sum(death_ch_pm)) %>% 
  top_n(n = 3, death_ch_pm) %>%
  mutate(three_share = sum(death_ch_pm) / nat_death) %>% 
  ggplot(mapping = aes(x = wk_date, y = death_ch_pm, label = code, fill = margin_2016)) +
  geom_label(na.rm = TRUE, position = position_jitter(width = 3, height = 25)) +
  labs(subtitle = str_c("Top 3 states in per capita COVID-19 deaths each week, through ", max(my_data$as_of, na.rm = TRUE), sep = " "),
       title = "States Trump won in 2016 have led death rates since late June",
       y = "Weekly deaths per million residents",
       x = NULL,
       fill = "Trump margin\nin 2016") +
  xlim(ymd(20200201), today()) +
  scale_fill_gradient2(low = "dodgerblue", aesthetics = "fill", high = "pink" , midpoint = 0)


```

```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(year_wk = str_c(year(as_of), week(as_of))) %>% 
  group_by(year_wk, code) %>% 
  summarize(case_ch_pm = 7 * mean(case_ch / pop_2019 * 1000000, na.rm = TRUE),
            death_ch_pm = 7 * mean(death_ch / pop_2019 * 1000000, na.rm = TRUE),
            is_hrc = sum(t_mgn, na.rm = TRUE) < 0,
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            wk_date = min(as_of, na.rm = TRUE)) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  group_by(wk_date) %>% 
  top_n(n = 3, case_ch_pm) %>%
  ggplot(mapping = aes(x = wk_date, y = case_ch_pm, label = code, fill = is_hrc)) +
  geom_label(na.rm = TRUE, position = position_jitter(width = 3, height = 25)) +
  theme(legend.position = "none") +
  labs(title = "Since June, states that voted for President Trump have led infection rates",
       subtitle = str_c("Three states with most new per capita COVID-19 cases by week through", max(my_data$as_of, na.rm = TRUE), sep = " "),
       y = "Weekly new COVID-19 cases per million residents",
       x = "Date") +
  xlim(ymd(20200301), today())


```


```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  inner_join(pop_dens) %>% 
  mutate(year_wk = week(as_of)) %>% 
  group_by(year_wk, reg_2, code, dens) %>% 
  summarize(case_ch_pm = 7 * mean(case_ch / pop_2019 * 1000000, na.rm = TRUE),
            death_ch_pm = 7 * mean(death_ch / pop_2019 * 1000000, na.rm = TRUE),
            is_hrc = sum(t_mgn, na.rm = TRUE) < 0,
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            wk_date = min(as_of, na.rm = TRUE)) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  group_by(wk_date) %>% 
  top_n(n = 3, case_ch_pm) %>%
  mutate(wk_dens = mean(dens, na.rm = TRUE)) %>% 
  ggplot(mapping = aes(x = wk_date, y = case_ch_pm)) +
  geom_label(mapping = aes(label = code, fill = reg_2), na.rm = TRUE, position = position_jitter(width = 3, height = 25)) +
  # geom_col(mapping = aes(y = wk_dens), alpha = .4) +
  labs(subtitle = str_c("Three states with most new per capita COVID-19 cases by week through", max(my_data$as_of, na.rm = TRUE), sep = " "),
       y = "Weekly new COVID-19 cases per million residents",
       x = "Date",
       legend = NULL
       # ,caption = "Gray bars represent mean population density of top states"
       ) +
  xlim(ymd(20200301), today()) +
  theme(legend.title = element_blank())


```

```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(year_wk = week(as_of)) %>% 
  group_by(year_wk, reg_2, code) %>% 
  summarize(case_ch_pm = 7 * mean(case_ch / pop_2019 * 1000000, na.rm = TRUE),
            death_ch_pm = 7 * mean(death_ch / pop_2019 * 1000000, na.rm = TRUE),
            is_hrc = sum(t_mgn, na.rm = TRUE) < 0,
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            wk_date = min(as_of, na.rm = TRUE)) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  group_by(wk_date) %>% 
  top_n(n = 3, case_ch_pm) %>%
  ggplot(mapping = aes(x = wk_date, y = death_ch_pm, label = code, fill = reg_2)) +
  geom_label(na.rm = TRUE, position = position_jitter(width = 3, height = 25)) +
  theme(
    # legend.position = "none"
    legend.title = element_blank()) +
  labs(subtitle = str_c("Top 3 states in per capita COVID-19 deaths by week, through ", max(my_data$as_of, na.rm = TRUE), sep = " "),
       y = "Weekly COVID-19 deaths per million residents",
       x = "Date") +
  xlim(ymd(20200301), today())


```


```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(year_wk = week(as_of)) %>% 
  group_by(year_wk, reg_2, code) %>% 
  summarize(case_ch_pm = 7 * mean(case_ch / pop_2019 * 1000000, na.rm = TRUE),
            death_ch_pm = 7 * mean(death_ch / pop_2019 * 1000000, na.rm = TRUE),
            is_hrc = sum(t_mgn, na.rm = TRUE) < 0,
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            wk_date = min(as_of, na.rm = TRUE)) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  group_by(wk_date) %>% 
  top_n(n = 5, case_ch_pm) %>%
  ggplot(mapping = aes(x = wk_date, y = case_ch_pm, label = code, fill = reg_2)) +
  geom_label(na.rm = TRUE, position = position_jitter(width = 3, height = 25)) +
  theme(legend.title = element_blank()) +
  labs(subtitle = str_c("Five states with most per capita COVID-19 cases through", max(my_data$as_of, na.rm = TRUE), sep = " "),
       y = "Weekly COVID-19 cases per million residents",
       x = "Date") +
  xlim(ymd(20200301), today())


```


```{r}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  inner_join(pop_dens) %>% 
  mutate(year_wk = week(as_of)) %>% 
  group_by(year_wk, reg_2, code, dens) %>% 
  summarize(case_ch_pm = 7 * mean(case_ch / pop_2019 * 1000000, na.rm = TRUE),
            death_ch_pm = 7 * mean(death_ch / pop_2019 * 1000000, na.rm = TRUE),
            is_hrc = sum(t_mgn, na.rm = TRUE) < 0,
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            wk_date = min(as_of, na.rm = TRUE)) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  group_by(wk_date) %>% 
  top_n(n = 3, case_ch_pm) %>%
  ggplot(mapping = aes(x = wk_date, y = death_ch_pm, label = code, fill = dens)) +
  geom_label(na.rm = TRUE, position = position_jitter(width = 3, height = 25), color = "black") +
  # theme(legend.position = "none") +
  labs(subtitle = str_c("Three states with most weekly per capita COVID-19 deaths through", max(my_data$as_of, na.rm = TRUE), sep = " "),
       y = "Weekly COVID-19 deaths per million residents",
       x = "Date",
       fill = "pop. per\nsq. mi.") +
  xlim(ymd(20200301), today()) +
  theme_bw() +
  scale_fill_gradientn(colors = c("orange", "white", "dodgerblue"))
```



```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  filter(as_of > today() - days(23),
           weekdays(as_of) == weekdays(max(as_of))) %>%
  mutate(is_max = (as_of == max(as_of))) %>% 
  group_by(code, is_max) %>% 
  summarize(as_of = mean(as_of, na.rm = TRUE),
            cases = mean(cases, na.rm = TRUE),
            death = mean(death, na.rm = TRUE),
            tests = mean(tests, na.rm = TRUE),
            is_clinton = (sum(t_mgn) < 0)) %>%
  group_by(code) %>% 
  ggplot() +
  geom_smooth(mapping = aes(x = code, y = cases, color = is_clinton), na.rm = TRUE, span = .07) +
  labs(x = "state", y = "Growth rate of COVID-19 cases", title = "Sun belt states saw the highest COVID-19 case growth rates in June", subtitle = "Growth rate of total COVID-19 cases from 1 to 30 June 2020 by state") +
  facet_wrap(facets = vars(code, nrow = 4)) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x  = element_blank(),
        strip.background = element_rect(fill = "lightgray"),
        legend.position = 0)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(is_clinton = t_mgn < 0) %>% 
  group_by(is_clinton, as_of) %>%
  summarize(case_ch_pm = sum(case_ch) / sum(pop_2019) * 1000000,
            death_ch_pm = sum(death_ch) / sum(pop_2019) * 1000000,
            cases_pm = sum(cases) / sum(pop_2019) * 1000000,
            death_pm = sum(death) / sum(pop_2019) * 1000000) %>% 
  filter(cases_pm >= 10) %>% 
  ggplot() +
  geom_smooth(mapping = aes(x = as_of, y = case_ch_pm, color = is_clinton, fill = is_clinton), alpha = 0.1, na.rm = TRUE, span = .1) +
  labs(x = "Date", y = "New cases per day per million", title = "States Trump won have had more COVID-19 cases per capita since June", subtitle = "Daily COVID-19 cases per million residents by state's 2016 winner") +
  theme(
    # axis.text = element_blank(),
    #     axis.ticks = element_blank(),
    #     axis.title.x  = element_blank(),
        # strip.background = element_rect(fill = "lightgray"),
        legend.position = 0)
```


Determine weekday factors
```{r}
wday_fact <- my_data %>% 
  filter(as_of >= today() - months(1)) %>% 
  mutate(wk_num = week(as_of),
         wkday = lubridate::wday(as_of),
         case_ch = if_else(case_ch == 0, 1L, case_ch),
         death_ch = if_else(death_ch == 0, 1L, death_ch)) %>% 
  group_by(code, wk_num) %>% 
  mutate(wday_case_local = case_ch / mean(case_ch, na.rm = TRUE),
         wday_death_local = death_ch / mean(death_ch, na.rm = TRUE)) %>% 
  ungroup() %>% 
  group_by(code, wkday) %>% 
  summarize(wday_case_global = mean(wday_case_local, na.rm = TRUE),
         wday_death_global = mean(wday_death_local, na.rm = TRUE))
         
  
  
```


```{r}
my_data %>% 
  mutate(wkday = lubridate::wday(as_of)) %>% 
  inner_join(wday_fact) %>% 
  filter(code == "CA", as_of > today() - weeks(2)) %>% 
  mutate(case_ch_adj = case_ch / wday_case_global,
         death_ch_adj = death_ch / wday_death_global,
         t_day = wkday + 1) %>% 
  mutate(day_name = lubridate::wday(x = t_day, label = TRUE)) %>%
  ggplot(mapping = aes(x = as_of)) +
  geom_line(mapping = aes(y = case_ch), color = "gray", size = 3) +
  geom_line(mapping = aes(y = case_ch_adj))


```



```{r}
my_data %>% 
  inner_join(wday_fact) %>% 
  inner_join(results_2016) %>% 
  group_by(code) %>%
  mutate(case_ch_adj = wday_case_global * case_ch,
         death_ch_adj = wday_death_global * death_ch,
         t_day = wkday + 1) %>% 
  filter(case_ch_adj == max(case_ch_adj, na.rm = TRUE) &
         as_of == max(as_of)) %>%
  mutate(day_name = lubridate::wday(x = t_day, label = TRUE)) %>% 
  ggplot(mapping = aes(x = code, y = case_ch_adj)) +
  geom_col() +
  geom_label(mapping = aes(label = day_name)) +
  labs(subtitle = "States with record adjusted new cases reported today")


```


```{r}
my_data %>% 
  inner_join(wday_fact) %>% 
  inner_join(results_2016) %>% 
  group_by(code) %>%
  mutate(case_ch_adj = wday_case_global * case_ch,
         death_ch_adj = wday_death_global * death_ch) %>% 
  filter(death_ch_adj == max(death_ch_adj, na.rm = TRUE) &
         as_of == max(as_of)) %>%
  mutate(day_name = lubridate::wday(wkday + 1, label = TRUE)) %>% 
  ggplot(mapping = aes(x = code, y = death_ch_adj)) +
  geom_col() +
  geom_label(mapping = aes(label = day_name)) +
  labs(subtitle = "States with record adjusted deaths reported today")


```

```{r}
pk <- c("CA", "CT", "MI", "NJ", "NY", "TX", "FL")

my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(year_wk = week(as_of)) %>% 
  filter(code %in% pk) %>% 
  group_by(year_wk, code) %>% 
  summarize(case_ch_pm = 7 * mean(case_ch / pop_2019 * 1000000, na.rm = TRUE),
            death_ch_pm = 7 * mean(death_ch / pop_2019 * 1000000, na.rm = TRUE),
            is_hrc = sum(t_mgn, na.rm = TRUE) < 0,
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            wk_date = min(as_of, na.rm = TRUE)) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  ggplot(mapping = aes(x = wk_date, y = death_ch_pm, label = code, fill = code, color = code)) +
  labs(subtitle = str_c("Compare some states through", max(my_data$as_of, na.rm = TRUE), sep = " "),
       y = "Weekly COVID-19 deaths per million residents",
       x = "Date") +
  xlim(ymd(20200301), today()) +
  geom_smooth(alpha = 0.1, span = .2) +
  theme_fivethirtyeight() +
  theme(legend.title = element_blank())

```


```{r}
nation_wk <- my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  mutate(year_wk = week(as_of)) %>% 
  # filter(code %in% c("CA")) %>% 
  group_by(year_wk) %>% 
  summarize(case_ch_pm = 7 * mean(sum(case_ch) / sum(pop_2019) * 1000000, na.rm = TRUE),
            death_ch_pm = 7 * mean(sum(death_ch) / sum(pop_2019) * 1000000, na.rm = TRUE),
            test_ch_pm = 7 * mean(sum(test_ch) / sum(pop_2019) * 1000000, na.rm = TRUE),
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE),
            wk_date = min(as_of, na.rm = TRUE)) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0)

```



```{r}

nation_wk %>% 
  ggplot(mapping = aes(x = wk_date, y = case_ch_pm)) +
  labs(subtitle = str_c("Per capita COVID-19 cases by week through", max(my_data$as_of, na.rm = TRUE), sep = " "),
       y = "Weekly COVID-19 cases per million residents",
       x = "Date") +
  xlim(ymd(20200301), today()) +
  geom_smooth(span = 0.2, na.rm = TRUE)

```



```{r}
nation_wk %>% 
  ggplot(mapping = aes(x = wk_date, y = death_ch_pm)) +
  labs(subtitle = str_c("Per capita COVID-19 deaths by week through", max(my_data$as_of, na.rm = TRUE), sep = " "),
       y = "Weekly COVID-19 deaths per million residents",
       x = "Date") +
  xlim(ymd(20200301), today()) +
  geom_line(na.rm = TRUE)
```


```{r}

my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>%
  inner_join(results_2016) %>% 
  filter(lubridate::wday(as_of) == lubridate::wday(max(as_of))) %>%
  # filter(code %in% c("CA")) %>% 
  group_by(as_of) %>%
  summarize(case_ch_pm = 7 * mean(sum(case_ch) / sum(pop_2019) * 1000000, na.rm = TRUE),
            death_ch_pm = 7 * mean(sum(death_ch) / sum(pop_2019) * 1000000, na.rm = TRUE),
            test_ch_pm = 7 * mean(sum(test_ch) / sum(pop_2019) * 1000000, na.rm = TRUE),
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE)) %>%
  filter(case_ch_pm > 0, death_ch_pm > 0) %>% 
  ggplot(mapping = aes(x = as_of, y = death_ch_pm)) +
  labs(subtitle = str_c("Per capita COVID-19 deaths by week through", max(my_data$as_of, na.rm = TRUE), sep = " "),
       y = "Weekly COVID-19 deaths per million residents",
       x = "Date") +
  xlim(ymd(20200301), today()) +
  geom_smooth(na.rm = TRUE, color = "dodgerblue", span = 0.15)
```


```{r}

cor_data <- my_data %>%
  select(as_of, code, case_ch, death_ch) %>% 
  filter(as_of > max(as_of) - months(6))
  

j <- data.table(code = character(), d_offset = integer(), cor_offset = double(), cfr = double())

st_vector <- code_names %>% select(code) %>% arrange(code) %>% pull(code)

for (k in st_vector) {
  
for (i in 10:40) {
j <- rbind(j,
           data.table(code = k,
                      d_offset = i,
                      cor_offset = cor_data %>%
                        filter(code == k) %>% 
                        mutate(d_lag = as_of + days(i)) %>%
                        left_join(cor_data[code == k], by = c("d_lag" = "as_of")) %>%
                        pull(-1) %>%
                        cor(x = ., y = cor_data[code == k]$case_ch, use = "complete.obs"),
           cfr = (cor_data[code == k & between(as_of, max(as_of) - 14, max(as_of))]$death) / (cor_data[code == k & between(as_of, max(as_of) -14 - i, max(as_of) - i)]$case_ch)))
}
  }




```



```{r}

case_death <- j %>% 
  group_by(code) %>% 
  arrange(desc(cor_offset)) %>% 
  slice_head()
  
```


```{r}

my_data %>%
  inner_join(case_death) %>%
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  group_by(code) %>% 
  filter(between(as_of, max(as_of, na.rm = TRUE) - d_offset + 1, max(as_of, na.rm = TRUE) - d_offset + 14)) %>% 
  mutate(as_of_proj = as_of + d_offset,
         wk_proj = if_else(as_of <= max(as_of, na.rm = TRUE) - 7, str_c("Week starting ", max(my_data$as_of) + days(1)), str_c("Week starting ", max(my_data$as_of) + days(8))),
         death_pm_proj_day = case_ch * cfr / pop_2019 * 1E6,
         two_wk = sum(death_pm_proj_day)) %>%
  ungroup() %>% 
  group_by(code, wk_proj, two_wk) %>%
  summarize(death_pm_proj_wk = sum(death_pm_proj_day, na.rm = TRUE)) %>% 
  ggplot(mapping = aes(y = death_pm_proj_wk, x = wk_proj, label = code)) +
  geom_label_repel(color = "chocolate4", fill = "forestgreen")
  
  
  


```

```{r}
case_death %>% 
  ggplot(mapping = aes(x = cfr)) +
  geom_histogram()
```


```{r}
lag_4wk_data <- my_data %>%
  select(as_of_lag_4wk = as_of, code, case_ch, test_ch) %>%
  filter(case_ch * test_ch > 0,
         test_ch >= case_ch) %>% 
  mutate(pos_rate_4wk = case_ch / test_ch) %>% 
  filter(pos_rate_4wk < 0.5) %>% 
  select(-test_ch, -case_ch)

lag_3wk_data <- my_data %>%
  select(as_of_lag_3wk = as_of, code, case_ch_3wk = case_ch) %>%
  filter(case_ch_3wk > 0) 


cor_data <- my_data %>%
  select(as_of, code, death_ch) %>% 
  filter(as_of > max(as_of) - months(6)) %>% 
  mutate(as_of_lag_4wk = as_of - weeks(4),
         as_of_lag_3wk = as_of - weeks(3)) %>%
  inner_join(lag_4wk_data) %>% 
  inner_join(lag_3wk_data)
```


```{r}
lag_1wk_data <- my_data %>%
  select(as_of_lag_1wk = as_of, code, case_ch, test_ch) %>%
  filter(case_ch > 0,
         test_ch > 0,
         test_ch >= case_ch) %>% 
  mutate(pos_rate_lag_1wk = case_ch / test_ch) %>% 
  filter(pos_rate_lag_1wk < 0.5,
         !is.na(pos_rate_lag_1wk)) %>% 
  select(-test_ch, -case_ch)

lead_3wk_data <- my_data %>%
  select(as_of_lead_3wk = as_of, code,
         death_ch_lead_3wk = death_ch) %>%
  filter(death_ch_lead_3wk > 0)


cor_data <- my_data %>%
  select(as_of, code, case_ch) %>% 
  filter(as_of > max(as_of) - months(10)) %>% 
  mutate(as_of_lag_1wk = as_of - weeks(1),
         as_of_lead_3wk = as_of + weeks(3)) %>%
  inner_join(lag_1wk_data) %>% 
  left_join(lead_3wk_data) %>% 
  arrange(desc(as_of_lead_3wk))


```


```{r}

# cor_data[code == "CA" & as_of > ymd(20201215)] %>% ggplot(aes(pos_rate_lag_1wk)) + geom_histogram()
# cor_data[code == "CA"] %>% ggplot(aes(as_of, pos_rate_lag_1wk)) + geom_line()
# 
# cor_data %>%
#   filter(code == 'CA',
#          as_of > ymd(20201201)) %>%
#   ggplot() +
#   geom_abline(slope = lm(cor_data[code == 'CA', death_ch_lead_3wk] ~ 0 + cor_data[code == 'CA', cor_data[code == 'CA', case_ch]])[[1]][[1]]) +
#   geom_abline(slope = lm(cor_data[code == 'CA', death_ch_lead_3wk] ~ 0 + cor_data[code == 'CA', cor_data[code == 'CA', case_ch]][[1]][[1]] + cor_data[code == 'CA', cor_data[code == 'CA', case_ch]])[[1]][[1]])
#   
# 
# lm(cor_data[code == 'CA', death_ch_lead_3wk])
# 
# 
# 
# cor_data %>%
#   filter(code == 'CA',
#          pos_rate_lag_1wk > 0.2) %>%
#   lm(formula = death_ch_lead_3wk ~ 0 + case_ch) %>% 
#   .[[1]]
# 
# cor_data %>%
#   filter(code == 'CA',
#          pos_rate_lag_1wk > 0.2) %>%
#   lm(formula = death_ch_lead_3wk ~ 0 + case_ch + pos_rate_lag_1wk) %>% 
#   .[[1]]
# 
# (1006 - 0103) / 103
```


```{r}
m_data <- data.table(survey_date = ymd(c(19660801, 19650501, 19640801, 19630501)), tot_fav = c(.33, .45, .44, .41), tot_unfav = c(.63, .46, .38, .37))
```

```{r}
m_data %>% 
  ggplot(mapping = aes(survey_date)) +
  geom_line(aes(y = tot_fav), color = "dodgerblue", size = 1.25) +
  geom_line(aes(y = tot_unfav), color = "darkgray", size = 1.25) +
  geom_label(aes(x = unique(m_data[year(survey_date) == 1964, survey_date]), y = unique(m_data[year(survey_date) == 1964, tot_fav]), label = "Favorable"), color = "dodgerblue") +
  geom_label(aes(x = m_data[year(survey_date) == 1965, survey_date], y = m_data[year(survey_date) == 1965, tot_unfav], label = "Unfavorable"), color = "dark gray") +
  geom_hline(aes(yintercept = .94), color = "lightblue", size = 1.25, linetype = "dashed") + geom_label(x = ymd(19650601), y = .94, label = "Favorable in Aug. 2011", color = "dodgerblue") +
  geom_hline(aes(yintercept = .04), color = "gray", size = 1.25, linetype = "dashed") + geom_label(x = ymd(19650601), y = .04, label = "Unfavorable in Aug. 2011", color = "darkgray") +
  labs(x = "Date",
       y = "Share of respondents by answer",
       caption = "Source: Contemporary poll data from Gallup\nhttps://tinyurl.com/y3zgrl5a",
       title = "While he lived, the public viewed MLK increasingly less favorably ")
```


```{r}
cor_test <- all_data %>%
  filter(state == "MS") %>% 
  mutate(yr_wk = str_c(year(ymd(date)), "-", lubridate::week(ymd(date)))) %>% 
  group_by(yr_wk) %>% 
  summarize(hospitalizedCurrently = mean(hospitalizedCurrently, na.rm = TRUE),
            inIcuCurrently = mean(inIcuCurrently, na.rm = TRUE),
            deathIncrease = sum(deathIncrease, na.rm = TRUE),
            hospitalizedIncrease = sum(hospitalizedIncrease, na.rm = TRUE),
            wk_ending = max(ymd(date))) %>% 
  data.table()

result_tbl <- data.table(lag = integer(), cor_hosp = double(), cor_icu = double())

for (i in 0:4) {
  temp_tbl <- cor_test[,lead_wk_ending := wk_ending + weeks(i)][,lead_deathIncrease := deathIncrease][,list(lead_deathIncrease, lead_wk_ending)] %>% 
  inner_join(cor_test[, list(hospitalizedCurrently, inIcuCurrently, wk_ending)], by = c("lead_wk_ending" = "wk_ending")) %>% 
    summarize(lag = i,
           cor_hosp = cor(hospitalizedCurrently, lead_deathIncrease, use = "pairwise.complete.obs"),
           cor_icu = cor(inIcuCurrently, lead_deathIncrease, use = "pairwise.complete.obs")) %>% 
    select(lag, cor_hosp, cor_icu)
  
result_tbl <- rbind(result_tbl, temp_tbl)
  
                       
}

result_tbl
```

