---
title: "For flight delays, when you depart is key"
# subtitle: "When you take off matters most"
output: html_notebook
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r eruptions, echo=FALSE, message=FALSE, warning=FALSE}
library(shiny); library(lubridate); library(tidyverse); library(ggthemes)

ui <- bootstrapPage( ## Define the UI
  dateInput(inputId = 'fly_date',
            label = 'Flight date',
            value = NULL,
            min = NULL,
            max = NULL,
            format = "yyyy-mm-dd",
            startview = "month",
            weekstart = 0,
            language = "en",
            width = NULL,
            autoclose = TRUE,
            datesdisabled = NULL,
            daysofweekdisabled = NULL),
  sliderInput(inputId = 'hr', label = 'Flight hour: ', min = 0, max = 23, value = 12, width = '100%'),
  sliderInput(inputId = 'min', label = 'Flight minute: ', min = 0, max = 59, value = 30, width = '100%'),
  plotOutput('plot')
)

# input$fly_date <- '2019-07-03'; input$hr <- 9; input$min <- 45

server <- function(input, output) { ## Define the server code
  output$plot <- renderPlot({
    
    coef <- tibble(mn = c(3.85236934,
                          -0.06363243,
                          -0.05417439,
                          -0.06181426,
                          -0.12503443,
                          -0.17237966,
                          -0.10804876,
                          -0.04541431,
                          -0.17399921),
                   se = c(0.0121161721,
                          0.0008861738,
                          0.0020117717,
                          0.0135075053,
                          0.0151832949,
                          0.0140442096,
                          0.0134079232,
                          0.0139179082,
                          0.0139245864))

    my_norm <- tibble(.rows = 10000)
    for(i in 1:9) my_norm[i] = rnorm(n = nrow(my_norm), mean = coef[[i, 1]], sd = coef[[i, 2]])

    my_pred <- my_norm %>%
      mutate(pred_delay = exp(V1 +
                                V2 * abs(input$hr + (input$min + 0.5) / 60 - 21.45) +
                                V3 * abs(month(ymd(input$fly_date)) + (day(ymd(input$fly_date)) - 0.5) /
                                           (days_in_month(ymd(input$fly_date))) - 5.31) +
                                V4 * (weekdays(ymd(input$fly_date)) == 'Monday') +
                                V5 * (weekdays(ymd(input$fly_date)) == 'Saturday') +
                                V6 * (weekdays(ymd(input$fly_date)) == 'Sunday') +
                                V7 * (weekdays(ymd(input$fly_date)) == 'Thursday') +
                                V8 * (weekdays(ymd(input$fly_date)) == 'Tuesday') +
                                V9 * (weekdays(ymd(input$fly_date)) == 'Wednesday')))
    
    mdn_pred = median(my_pred$pred_delay)
    
    p_on_time <- 1 /
      (1 + exp(-(-0.868973986936626 +
                   0.132485588024036 * abs(input$hr + (input$min + 0.5) / 60 - 21.45) +
                   0.0938310236036926 * abs(month(ymd(input$fly_date)) + (day(ymd(input$fly_date)) - 0.5) /
                                              (days_in_month(ymd(input$fly_date))) - 5.31) +
                   0.152317762763714 * (weekdays(ymd(input$fly_date)) == 'Monday') +
                   0.312356993431681 * (weekdays(ymd(input$fly_date)) == 'Saturday') +
                   0.323550415257237 * (weekdays(ymd(input$fly_date)) == 'Sunday') +
                   0.0979982073199806 * (weekdays(ymd(input$fly_date)) == 'Thursday') +
                   0.265313809910303 * (weekdays(ymd(input$fly_date)) == 'Tuesday') +
                   0.316247648362565 * (weekdays(ymd(input$fly_date)) == 'Wednesday'))))
    
    is_delayed <- runif(10000) > p_on_time
    
    my_pred %>%
      ggplot() +
      geom_histogram(mapping = aes(my_pred$pred_delay, color = is_delayed), bins = 50) +
      ggtitle(paste('Chance of on-time departure is',round(100*p_on_time),'percent'),
              paste('But if there is a delay it will be around',round(mdn_pred),'minutes')) +
      theme_fivethirtyeight() +
      scale_color_fivethirtyeight()
    
    
        # plot(x = rep(round(input$hr * 100 +input$min, 1), 3),
        #  y = c(100/(1+exp(-(0.279603750 - (0.001999519 - 0.0000148) * abs(input$hr * 60 + input$min - (19 * 60 + 35))))),
        #        100/(1+exp(-(0.279603750 - 0.001999519 * abs(input$hr * 60 + input$min - (19 * 60 + 35))))),
        #        100/(1+exp(-(0.279603750 - (0.001999519 + 0.0000148) * abs(input$hr * 60 + input$min - (19 * 60 + 35)))))),
        #  xlim = range(input$hr * 100, input$hr * 100 + 55),
        #  type = 'b',
        #  lwd = 3,
        #  lty = 2,
        #  tck = 0.02,
        #  xlab = input$fly_date,
        #  ylab = 'Percent chance of delay, with std. err. bars',
        #  pch = 3,
        #  main = paste('Plan around a chance of delay of ', round(100/(1+exp(-(0.279603750 - (0.001999519) * abs(input$hr * 60 + input$min - (19 * 60 + 35)))))), '%'))
  })
}
shinyApp(ui = ui, server = server) ## Return a Shiny app object
```

