---
title: "US COVID-19 Dashboard"
output:
  html_document:
    df_print: paged
---

load libraries

```{r include=FALSE}
library(shiny)
library(jsonlite)
library(data.table)
library(tidyverse)
library(lubridate)
library(ggthemes)
library(gridExtra)



options(scipen = 999)
```



Load static data

```{r include=FALSE}
static_data <- data.table(name = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"), 
state = c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"), 
pop = c(4908620, 734002, 7378490, 3039000, 39937500, 5845530, 3563080, 982895, 21993000, 10736100, 1412690, 1826160, 12659700, 6745350, 3179850, 2910360, 4499690, 4645180, 1345790, 6083120, 6976600, 10045000, 5700670, 2989260, 6169270, 1086760, 1952570, 3139660, 1371250, 8936570, 2096640, 19440500, 10611900, 761723, 11747700, 3954820, 4301090, 12820900, 1056160, 5210100, 903027, 6897580, 29472300, 3282120, 628061, 8626210, 7797100, 1778070, 5851750, 567025, 705749),
area = c(50645, 570641, 113594, 52035, 155779, 103642, 4842, 1949, 53625, 57513, 6423, 82643, 55519, 35826, 55857, 81759, 39486, 43204, 30843, 9707, 7800, 56539, 79627, 46923, 68742, 145546, 76824, 109781, 8953, 7354, 121298, 47126, 48618, 69001, 40861, 68595, 95988, 44743, 1034, 30061, 75811, 41235, 261232, 82170, 9217, 39490, 66456, 24038, 54158, 97093, 68.3),
region = c("South", "Sky", "Southwest", "Middle South", "West Coast", "Southwest", "Northeast", "Northeast", "South", "South", "West Coast", "Sky", "Midwest", "Midwest", "Midwest", "Sky", "Middle South", "South", "Northeast", "Northeast", "Northeast", "Midwest", "Midwest", "South", "Midwest", "Sky", "Sky", "Southwest", "Northeast", "Northeast", "Southwest", "Northeast", "South", "Sky", "Midwest", "Sky", "West Coast", "Northeast", "Northeast", "South", "Sky", "Middle South", "Southwest", "Sky", "Northeast", "South", "West Coast", "Middle South", "Midwest", "Sky", "Northeast"))[, c("pop", "pop_dens") := list(as.integer(pop), pop / area)]

```


Pull data
```{r include=FALSE}
all_data <- data.table(fromJSON("https://covidtracking.com/api/v1/states/daily.json"))
```


```{r}
all_data_cdc <- data.table(fromJSON("https://data.cdc.gov/resource/9mfq-cb36.json"))
```





```{r}
all_data_cdc[state == "CA"] %>%
  arrange(desc(submission_date))
```



```{r include=FALSE}
data_date <- ymd(max(all_data[,date], na.rm = TRUE))

date_to_wk <- function(date_input) {case_when(wday(ymd(date_input)) == wday(data_date) ~ ymd(date_input),
          wday(ymd(date_input)) < wday(data_date) ~ ymd(date_input) + days(wday(data_date) - wday(ymd(date_input))),
          TRUE ~ ymd(date_input) + days(7 + wday(data_date) - wday(ymd(date_input))))}
```



```{r message=FALSE, warning=FALSE, include=FALSE}
clean_data <- all_data[state %in% static_data[,state],][
  ,wk_ending := date_to_wk(date)][
                            ,c("death",
                               "positiveIncrease",
                               "negativeIncrease",
                               "totalTestResultsIncrease",
                               "deathIncrease") := list(max(death, na.rm = TRUE),
                                                               sum(positiveIncrease, na.rm = TRUE),
                                                               sum(negativeIncrease, na.rm = TRUE),
                                                               sum(totalTestResultsIncrease, na.rm = TRUE),
                                                               sum(deathIncrease, na.rm = TRUE)),
                            by = list(state, wk_ending)][
                              ymd(date) == wk_ending,
                              list(wk_ending,
                                   state,
                                   death,
                                   positiveIncrease,
                                   negativeIncrease,
                                   totalTestResultsIncrease,
                                   deathIncrease)] %>%
  left_join(unique(all_data[,lead3_wk_ending := date_to_wk(date)][
    ,lead3_deathIncrease := sum(deathIncrease, na.rm = TRUE), by = list(state, lead3_wk_ending)][
      ,wk_ending := lead3_wk_ending - weeks(3)][
        ,list(lead3_wk_ending, state, lead3_deathIncrease, wk_ending)]), by = c("wk_ending", "state")) %>% 
  inner_join(unique(all_data[,lag1_wk_ending := date_to_wk(date)][
    ,lag1_pos := sum(positiveIncrease, na.rm = TRUE) / sum(totalTestResultsIncrease, na.rm = TRUE), by = list(state, lag1_wk_ending)][
      ,wk_ending := lag1_wk_ending + weeks(1)][
        ,list(lag1_wk_ending, state, lag1_pos, wk_ending)]), by = c("wk_ending", "state")) %>% 
  filter(!is.na(lag1_pos) & !is.na(positiveIncrease) & !is.infinite(lag1_pos) & !is.infinite(positiveIncrease))

```



```{r}

coeff_tbl <- data.table(state = character(), est_case = double(), est_pos = double(), est_casepos_case = double(), est_casepos_pos = double())
  
for (i in static_data[, state]) {
  temp_tbl <- data.table(state = i,
                         est_case = lm(lead3_deathIncrease ~ 0 + positiveIncrease, clean_data[state == i & wk_ending > data_date - months(6)])[[1]][[1]],
                         est_pos = lm(lead3_deathIncrease ~ 0 + lag1_pos, clean_data[state == i & wk_ending > data_date - months(6)])[[1]][[1]],
                         est_casepos_case = lm(lead3_deathIncrease ~ 0 + positiveIncrease + lag1_pos, clean_data[state == i & wk_ending > data_date - months(6)])[[1]][[1]],
                         est_casepos_pos = lm(lead3_deathIncrease ~ 0 + positiveIncrease + lag1_pos, clean_data[state == i & wk_ending > data_date - months(6)])[[2]][[1]])
  coeff_tbl <- rbindlist(l = list(coeff_tbl, temp_tbl))
}

coeff_tbl[est_casepos_pos < 0, c("est_casepos_case", "est_casepos_pos") := list(est_case, 0)]
setkey(coeff_tbl, state)

```

```{r}
setkey(clean_data, state)

proj_data <- clean_data[coeff_tbl][
  is.na(lead3_wk_ending), c("lead3_deathIncrease", "lead3_wk_ending", "death_proj") := list(round(est_casepos_case * positiveIncrease + est_casepos_pos * lag1_pos, 0), wk_ending + weeks(3), TRUE)][
    is.na(death_proj), death_proj := FALSE][
      wk_ending > data_date - months(1), truecase_increase := est_pos * lag1_pos / est_casepos_case][
        ,truecase_increase := if_else(truecase_increase < positiveIncrease, as.double(positiveIncrease), truecase_increase)]
```

7-month trend
```{r}
grob_trend <- proj_data %>%
  filter(wk_ending > today() - months(9)) %>% 
  group_by(wk_ending, death_proj) %>% 
  summarize(deathIncrease = sum(deathIncrease)) %>% 
  ggplot(mapping = aes(x = wk_ending, y = deathIncrease, fill = death_proj, linetype = death_proj, color = death_proj)) +
  theme_bw() +
  geom_col(size = 1.2) +
  scale_fill_discrete(type = c("darkgray", "white")) +
  scale_color_discrete(type = c("dodgerblue", "darkgray")) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "U.S. COVID-19 deaths may drop", subtitle = str_c("Week ending ", data_date), x = NULL)

grob_trend
```

compare cases
```{r}
grob_case <- proj_data %>%
  inner_join(static_data[,list(state, pop, name)]) %>% 
  mutate(truecase_increase = truecase_increase / pop * 1000,
         positiveIncrease = positiveIncrease / pop * 1000,
         truecase_increase = if_else(truecase_increase > 2 * positiveIncrease, 2 * positiveIncrease, truecase_increase),
         undercount <<- max((truecase_increase - positiveIncrease) / truecase_increase, na.rm = TRUE)) %>% 
  filter(wk_ending == data_date,
         truecase_increase > quantile(positiveIncrease, .75) |
           state %in% c("AZ", "CA", "TX", "NY", "FL")) %>% 
  ggplot(mapping = aes(x = reorder(x = state, X = positiveIncrease))) +
  geom_col(mapping = aes(y = truecase_increase), fill = "white", color = "black", linetype = "dashed") +
  geom_col(mapping = aes(y = positiveIncrease, fill = lag1_pos), color = "black") +
  labs(x = NULL, y = "Case increase per thousand",
       title = str_c(top_n(clean_data[static_data, on = "state"][wk_ending == data_date], 1, wt = positiveIncrease / pop)[,name], " leads in confirmed cases this past week, but many\nstates are likely counting fewer than half their actual cases"),
       subtitle = str_c("Confirmed COVID-19 cases week ending ", data_date)) +
  coord_flip() +
  theme_bw() +
  theme(legend.position = "none")


grob_case
```


```{r}
grob_death_week <- proj_data %>%
  inner_join(static_data[,list(state, pop)]) %>% 
  mutate(lead3_deathIncrease = lead3_deathIncrease / pop * 1E6) %>% 
  filter(lead3_wk_ending == data_date,
         lead3_deathIncrease > quantile(lead3_deathIncrease, .85) |
           state %in% c("AZ", "CA", "TX", "NY", "FL")) %>% 
  inner_join(unique(proj_data[death_proj == TRUE, list(state, lead3_deathIncrease)][, tot_proj := sum(lead3_deathIncrease), by = state][,list(state, tot_proj)][static_data[,list(state, pop)], on = "state"][,proj_pm := tot_proj / pop])) %>% 
  ggplot(mapping = aes(x = reorder(x = state, X = lead3_deathIncrease))) +
  geom_col(mapping = aes(y = lead3_deathIncrease), fill = "white", color = "black", linetype = "dashed") +
  geom_col(mapping = aes(y = lead3_deathIncrease, fill = proj_pm), color = "black") +
  labs(x = NULL, y = "Weekly deaths per million", title = str_c(top_n(clean_data[static_data, on = "state"][wk_ending == data_date], 1, wt = deathIncrease / pop)[,state], " sits atop weekly COVID-19 death rate through ", data_date)) +
  theme_bw() +
  theme(legend.position = "none") +
  coord_flip()

grob_death_week
```


```{r}
grob_cum <- proj_data %>%
  inner_join(static_data[,list(state, pop, pop_dens)]) %>% 
  mutate(death = death / pop * 1E6) %>%
  filter(wk_ending == data_date,
         death > quantile(death, .96, na.rm = TRUE) |
           state %in% c("AZ", "CA", "TX", "NY", "FL")) %>% 
  ggplot(mapping = aes(x = reorder(x = state, X = death))) +
  geom_col(mapping = aes(y = death), fill = "white", color = "black", linetype = "dashed") +
  geom_col(mapping = aes(y = death, fill = pop_dens), color = "black") +
  labs(x = NULL, y = "COVID-19 deaths per million", title = "Top states in COVID-19 deaths per capita may be dense or sparse") +
  coord_flip() +
  theme(legend.position = "none") +
  theme_bw()

grob_cum
```



```{r}
grid.arrange(grob_case, grob_death_week, grob_trend, grob_cum)
```

