---
title: "U.S. COVID-19 dashboard"
output:
  html_document:
    df_print: paged
---



```{r message=FALSE, warning=FALSE, include=FALSE}

library(lubridate)
library(data.table)
library(tidyverse)
library(jsonlite)
library(ggrepel)
library(stringr)
library(ggthemes)

```


```{r Load_COVID_data, message=FALSE, warning=FALSE, include=FALSE}
all_data <- fromJSON("https://covidtracking.com/api/v1/states/daily.json") %>% as.data.table()
```


```{r Narrow_data, message=FALSE, warning=FALSE, include=FALSE}
my_data <- all_data %>% 
  mutate(as_of = ymd(date), tests = positive + negative, test_ch = positiveIncrease + negativeIncrease) %>% 
  select(as_of, code = state, cases = positive, case_ch = positiveIncrease, death, death_ch = deathIncrease, tests, test_ch) %>% 
  data.table()
```


```{r Adding_state_pop, include=FALSE}
st_pop_2019 <- read_csv("st_pop.csv") %>% 
  select(name = 5, pop_2019 = 17) %>% 
  mutate(pop_2019 = as.integer(pop_2019))
```


```{r Load_regions, message=FALSE, warning=FALSE, include=FALSE}
code_names <- data.table(cbind(name = c(state.name, "District of Columbia"),
                 code = c(state.abb, "DC"),
                 region = as.character(state.region),
                 reg_2 = c("South", "Plain and Mountain", "Southwest", "Middle South", "West Coast", "Southwest", "Northeast", "Northeast", "South", "South",
                           "West Coast", "Plain and Mountain", "Midwest", "Midwest", "Midwest", "Plain and Mountain", "Middle South", "South", "Northeast", "Northeast",
                           "Northeast", "Midwest", "Midwest", "South", "Midwest", "Plain and Mountain", "Plain and Mountain", "Southwest", "Northeast", "Northeast",
                           "Southwest", "Northeast", "South", "Plain and Mountain", "Midwest", "Plain and Mountain", "West Coast", "Northeast", "Northeast", "South",
                           "Plain and Mountain", "Middle South", "Southwest", "Plain and Mountain", "Northeast", "South", "West Coast", "Middle South", "Midwest", "Plain and Mountain",
                           "Northeast")))
```


```{r load_pop_density_by_state, message=FALSE, warning=FALSE, include=FALSE}
pop_dens <- read_csv(file = "pop_density.csv", col_types = "-cdi-")
```


```{r calc_lifetime_data, echo=FALSE, message=FALSE, warning=FALSE}
lifetime_data <- my_data %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  filter(lubridate::wday(as_of) == lubridate::wday(max(as_of))) %>%
  mutate(is_ca = if_else(code == "CA", "Calif.", "Rest of US")) %>%
  group_by(
    is_ca,
    as_of) %>% 
  summarize(cases = sum(cases, na.rm = TRUE),
            deaths = sum(death, na.rm = TRUE),
            tests = sum(tests, na.rm = TRUE),
            cases_pm = sum(cases, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000,
            deaths_pm =  sum(death, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000,
            tests_pm = sum(tests, na.rm = TRUE) / sum(pop_2019, na.rm = TRUE) * 1000000,
            pos_rate = cases / tests) %>% 
  mutate(case_ch_pm = cases_pm - lag(cases_pm),
         death_ch_pm = deaths_pm - lag(deaths_pm),
         test_ch_pm = tests_pm - lag(tests_pm)) %>% 
  data.table()
```


```{r include=FALSE}
weekly_data <- code_names %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(my_data) %>% 
  group_by(code, reg_2) %>%  
  filter(as_of >= max(as_of) - weeks(1)) %>%
  summarize(test_weekly_growth = round((max(tests) - min(tests)) / min(tests), 2),
            test_weekly_pm = signif(((max(tests) - min(tests)) / mean(pop_2019) * 1000000), 3),
            case_weekly_growth = round((max(cases) - min(cases)) / min(cases), 2),
            case_weekly_pm = signif(((max(cases) - min(cases)) / mean(pop_2019) * 1000000), 3),
            death_weekly_growth = round((max(death) - min(death)) / min(death), 2),
            death_weekly_pm = signif(((max(death) - min(death)) / mean(pop_2019) * 1000000), 3),
            test_weekly = max(tests, na.rm = TRUE) - min(tests, na.rm = TRUE),
            case_weekly = max(cases, na.rm = TRUE) - min(cases, na.rm = TRUE),
            death_weekly = max(death, na.rm = TRUE) - min(death, na.rm = TRUE),
            wk_ending = max(as_of),
            pos_rate = sum(case_ch, na.rm = TRUE) / sum(test_ch, na.rm = TRUE)) %>% 
  data.table()
```


```{r include=FALSE}
monthly_data <- code_names %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(my_data) %>% 
  group_by(code, reg_2) %>%  
  filter(as_of >= max(as_of) - months(1)) %>%
  summarize(test_monthly_growth = round((max(tests) - min(tests)) / min(tests), 2),
            test_monthly_pm = signif(((max(tests) - min(tests)) / mean(pop_2019) * 1000000), 3),
            case_monthly_growth = round((max(cases) - min(cases)) / min(cases), 2),
            case_monthly_pm = signif(((max(cases) - min(cases)) / mean(pop_2019) * 1000000), 3),
            death_monthly_growth = round((max(death) - min(death)) / min(death), 2),
            death_monthly_pm = signif(((max(death) - min(death)) / mean(pop_2019) * 1000000), 3),
            mo_ending = max(as_of))
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
lag_4wk_data <- my_data %>%
  select(as_of_lag_4wk = as_of, code, case_ch, test_ch) %>%
  filter(case_ch * test_ch > 0,
         test_ch >= case_ch) %>% 
  mutate(pos_rate_4wk = case_ch / test_ch) %>% 
  filter(pos_rate_4wk < 0.5) %>% 
  select(-test_ch, -case_ch)

lag_3wk_data <- my_data %>%
  select(as_of_lag_3wk = as_of, code, case_ch_3wk = case_ch) %>%
  filter(case_ch_3wk > 0) 


cor_data <- my_data %>%
  select(as_of, code, death_ch) %>% 
  filter(as_of > max(as_of) - months(6)) %>% 
  mutate(as_of_lag_4wk = as_of - weeks(4),
         as_of_lag_3wk = as_of - weeks(3)) %>%
  inner_join(lag_4wk_data) %>% 
  inner_join(lag_3wk_data)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
lag_1wk_data <- my_data %>%
  select(as_of_lag_1wk = as_of, code, case_ch, test_ch) %>%
  filter(case_ch > 0,
         test_ch > 0,
         test_ch >= case_ch) %>% 
  mutate(pos_rate_lag_1wk = case_ch / test_ch) %>% 
  filter(pos_rate_lag_1wk < 0.5,
         !is.na(pos_rate_lag_1wk)) %>% 
  select(-test_ch, -case_ch)

lead_3wk_data <- my_data %>%
  select(as_of_lead_3wk = as_of, code,
         death_ch_lead_3wk = death_ch) %>%
  filter(death_ch_lead_3wk > 0)


cor_data <- my_data %>%
  select(as_of, code, case_ch) %>% 
  filter(as_of > ymd(20200501),
         between(case_ch, 1, 50000)) %>% 
  mutate(as_of_lag_1wk = as_of - weeks(1),
         as_of_lead_3wk = as_of + weeks(3)) %>%
  inner_join(lag_1wk_data) %>% 
  left_join(lead_3wk_data) %>% 
  arrange(desc(as_of_lead_3wk))


```


```{r echo=FALSE, message=FALSE, warning=FALSE}

proj_table <- data.table(code = character(),
                         as_of_lead_3wk = Date(),
                         death_ch_lead_3wk = integer(),
                         death_ch_proj = double(),
                         death_ch_proj_se = double())

for (i in code_names$code) {

temp_tbl <- cor_data %>%
    filter(code %in% i)

proj_table <- rbind(proj_table,
                    data.table(code = temp_tbl$code,
                               as_of_lead_3wk = temp_tbl$as_of_lead_3wk,
                               death_ch_lead_3wk = temp_tbl$death_ch_lead_3wk,
                               death_ch_proj = temp_tbl[,case_ch] *
                                          summary(lm("death_ch_lead_3wk ~ 0 + case_ch + pos_rate_lag_1wk", temp_tbl, na.action = na.omit))[[4]][1] +
                                          temp_tbl[,pos_rate_lag_1wk] *
                                          summary(lm("death_ch_lead_3wk ~ 0 + case_ch + pos_rate_lag_1wk", temp_tbl, na.action = na.omit))[[4]][2],
                               death_ch_proj_se = temp_tbl[,case_ch] *
                                          summary(lm("death_ch_lead_3wk ~ 0 + case_ch + pos_rate_lag_1wk", temp_tbl, na.action = na.omit))[[4]][3] +
                                          temp_tbl[,pos_rate_lag_1wk] *
                                          summary(lm("death_ch_lead_3wk ~ 0 + case_ch + pos_rate_lag_1wk", temp_tbl, na.action = na.omit))[[4]][4]))
}
  


## case_ch coeff summary(lm("death_ch_lead_3wk ~ 0 + case_ch + pos_rate_lag_1wk", temp_tbl, na.action = na.omit))[[4]][1]
## case_ch coeff SE summary(lm("death_ch_lead_3wk ~ 0 + case_ch + pos_rate_lag_1wk", temp_tbl, na.action = na.omit))[[4]][3]
## pos_rate_lag_1wk coeff summary(lm("death_ch_lead_3wk ~ 0 + case_ch + pos_rate_lag_1wk", temp_tbl, na.action = na.omit))[[4]][2]
## pos_rate_lag_1wk coeff SE summary(lm("death_ch_lead_3wk ~ 0 + case_ch + pos_rate_lag_1wk", temp_tbl, na.action = na.omit))[[4]][4]



```


```{r echo=FALSE, message=FALSE, warning=FALSE}
proj_sum <- proj_table %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  filter(as_of_lead_3wk > max(my_data$as_of, na.rm = TRUE)) %>% 
  group_by(code, reg_2) %>% 
  summarize(death_3wk_proj = sum(death_ch_proj, na.rm = TRUE) / pop_2019 * 1000000) %>% 
  unique()
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
weekly_proj <- my_data %>% 
  right_join(proj_table, by = c("as_of" = "as_of_lead_3wk" , "code")) %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  mutate(death_ch_proj = if_else(as_of > max(my_data$as_of, na.rm = TRUE), death_ch_proj, as.double(death_ch)),
         wk_ending = case_when(wday(as_of) == wday(max(my_data$as_of, na.rm = TRUE)) ~
                                 as_of,
                               wday(as_of) < wday(max(my_data$as_of, na.rm = TRUE)) ~
                                 as_of + days(wday(max(my_data$as_of, na.rm = TRUE)) - wday(as_of)),
                               wday(as_of) > wday(max(my_data$as_of, na.rm = TRUE)) ~
                                 as_of + days(7 + wday(max(my_data$as_of, na.rm = TRUE)) - wday(as_of)))) %>% 
  group_by(wk_ending) %>% 
  summarize(tot_death_ch = sum(death_ch),
            tot_death_ch_proj = sum(death_ch_proj)) %>% 
  data.table()

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
temp_tbl <- proj_table %>% 
  mutate(wk_ending = case_when(wday(as_of_lead_3wk) == wday(max(my_data$as_of, na.rm = TRUE)) ~
                                 as_of_lead_3wk,
                               wday(as_of_lead_3wk) < wday(max(my_data$as_of, na.rm = TRUE)) ~
                                 as_of_lead_3wk + days(wday(max(my_data$as_of, na.rm = TRUE)) - wday(as_of_lead_3wk)),
                               wday(as_of_lead_3wk) > wday(max(my_data$as_of, na.rm = TRUE)) ~
                                 as_of_lead_3wk + days(7 + wday(max(my_data$as_of, na.rm = TRUE)) - wday(as_of_lead_3wk)))
         # ,is_ca = (code == "CA")
         ) %>% 
  group_by(wk_ending
           # , is_ca
           ) %>% 
  summarize(death_ch_us = sum(death_ch_lead_3wk, na.rm = TRUE),
            death_ch_proj_us = sum(death_ch_proj, na.rm = TRUE)) %>% 
  # mutate(death_ch_us = if_else(is_ca, death_ch_us * 7,
  #                              as.double(death_ch_us)),
  #        death_ch_proj_us = if_else(is_ca, death_ch_proj_us * 7,
  #                                   death_ch_proj_us)) %>% 
  data.table()
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot() +
  theme_bw() +

  geom_col(mapping = aes(x = temp_tbl[, wk_ending], y = temp_tbl[,death_ch_us]), size = 1, na.rm = TRUE, color = "dodgerblue") +
  geom_col(mapping = aes(x = temp_tbl[wk_ending > max(my_data$as_of, na.rm = TRUE), wk_ending], y = temp_tbl[wk_ending > max(my_data$as_of, na.rm = TRUE), death_ch_proj_us]), na.rm = TRUE, size = 1, fill = "white", color = "darkgray", linetype = "dashed") +
  
  # geom_col(mapping = aes(x = temp_tbl[is_ca == FALSE, wk_ending], y = temp_tbl[is_ca == FALSE, death_ch_us]), size = 1, na.rm = TRUE, color = "dodgerblue") +
  # geom_col(mapping = aes(x = temp_tbl[is_ca == FALSE & wk_ending > max(my_data$as_of, na.rm = TRUE), wk_ending], y = temp_tbl[is_ca == FALSE & wk_ending > max(my_data$as_of, na.rm = TRUE), death_ch_proj_us]), na.rm = TRUE, size = 1, fill = "white", color = "darkgray", linetype = "dashed") +
  
  
  theme(legend.title = element_blank()) +
  labs(x = "Date", y = "Deaths per million per week", title = str_c("The US saw ",
                                                           sum(weekly_data$death_weekly, na.rm = TRUE),
                                                           " deaths week ending ",
                                                            max(my_data$as_of, na.rm = TRUE),
                                                           " to a total of ",
                                                           sum(lifetime_data[as_of == max(as_of, na.rm = TRUE), deaths]),
                                                           "\nand may see ", signif(sum(proj_table[as_of_lead_3wk > max(my_data$as_of, na.rm = TRUE), death_ch_proj], na.rm = TRUE), 3), " more deaths over the next 3 weeks ending ", max(my_data$as_of, na.rm = TRUE) + weeks(3)))
       # ,caption = "California data normalized using a factor of 7"
       

  
  
  #  + geom_line(mapping = aes(x = temp_tbl[is_ca == TRUE & wk_ending <= max(my_data$as_of, na.rm = TRUE), wk_ending], y = temp_tbl[is_ca == TRUE & wk_ending <= max(my_data$as_of, na.rm = TRUE), death_ch_us]), size = 1, na.rm = TRUE, color = "orange") +
  # geom_line(mapping = aes(x = temp_tbl[is_ca == TRUE & wk_ending > max(my_data$as_of, na.rm = TRUE), wk_ending], y = temp_tbl[is_ca == TRUE & wk_ending > max(my_data$as_of, na.rm = TRUE), death_ch_proj_us]), size = 1, na.rm = TRUE, color = "darkorange", linetype = "dashed") 

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
tot_data <- my_data %>%
  filter(as_of == max(as_of, na.rm = TRUE)) %>% 
  inner_join(code_names) %>% 
  inner_join(pop_dens) %>% 
  mutate(death_pm = death / Pop * 1E6) %>% 
  data.table()

tot_data %>% 
  filter(death_pm > quantile(tot_data[,death_pm], probs = .7, na.rm = TRUE) | code == "CA") %>% 
  ggplot() +
  geom_col(mapping = aes(x = reorder(code, X = desc(death_pm)), y = death_pm, fill = Density), color = "dodgerblue") +
  labs(x = "state", y = "Weekly deaths per million residents", title = stringr::str_c("States with most cumulative deaths per million"), subtitle = str_c("As of ", max(tot_data[,as_of]), sep = " ")) +
  scale_fill_gradient2(low = "white", mid = "white", high = "dodgerblue")
  # + theme(legend.title=element_blank(), axis.text.x = element_text(angle = 90, size = 8))
```



```{r impute_cases_from_death, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
c2t_data <- cor_data %>%
  inner_join(select(my_data, as_of, code, test_ch)) %>%
  mutate(pos_rate = case_ch / test_ch,
         death_ch_lead_3wk = as.double(death_ch_lead_3wk),
         cfr = death_ch_lead_3wk / case_ch) %>%
  filter(as_of > mdy(06012020),
         !is.na(death_ch_lead_3wk),
         between(pos_rate, 0.005, 0.50)) %>% 
  data.table()
           
c2t_coeff <- data.table(code = character(), coeff = double())

for (i in code_names[,code]) {
  c2t_coeff <- rbind(c2t_coeff,
                     data.table(code = i,
                                coeff = lm(data = c2t_data[code == i,],
                                           formula = cfr ~ pos_rate)[[1]][[1]]))
}
```


```{r impute_cases_from_posrate, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
case_model <- c2t_data %>% 
  inner_join(c2t_coeff) %>% 
  mutate(case_ch_model = death_ch_lead_3wk / coeff) %>% 
  unique() %>%
  mutate(wk_ending = case_when(wday(as_of) == wday(max(my_data$as_of, na.rm = TRUE))
                               ~ as_of,
                               wday(as_of) < wday(max(my_data$as_of, na.rm = TRUE))
                               ~  as_of + days(wday(max(my_data$as_of, na.rm = TRUE)) - wday(as_of)),
                               wday(as_of) > wday(max(my_data$as_of, na.rm = TRUE))
                               ~ as_of + days(7 + wday(max(my_data$as_of, na.rm = TRUE)) - wday(as_of)))) %>% 
  data.table()
```


```{r impute_cases_from_posrate_2, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
case_model_st_wk <- case_model %>%
  group_by(wk_ending, code) %>% 
  summarize(case_ch = sum(case_ch),
            case_ch_model = sum(case_ch_model),
            pos_rate = sum(case_ch) / sum(test_ch),
            pos_rate_lag_1wk = mean(pos_rate_lag_1wk),
            cfr = sum(death_ch_lead_3wk) / sum(case_ch),
            c2t = case_ch * pos_rate) %>%
  filter(cfr <= 0.2, between(pos_rate, 0.1, 0.30)) %>% 
  data.table()

case_model_st_wk %>% 
  mutate(case_ch = case_ch / case_ch_model,
         case_ch_model = 1) %>% 
  ggplot(aes(pos_rate)) +
  geom_smooth(aes(y = cfr))
  
  # inner_join(pop_dens) %>%
  # mutate(case_ch_pm = tot_case_ch / Pop * 1000000,
  #        case_ch_model_pm = case_ch_model / Pop * 1000000) %>% 
  # slice_max(order_by = case_ch_model_pm, n = 15) %>% 
  # ggplot(mapping = aes(x = reorder(code, desc(case_ch_pm)))) +
  # geom_col(mapping = aes(y = case_ch_model_pm), fill = "lightgray", color = "darkgray", size = 1, linetype = "dashed") +
  # geom_col(mapping = aes(y = case_ch_pm), fill = "darkgray", color = "dodgerblue", size = 1)


## As pos rate approaches 0.5 
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
all_data %>%
  filter(date == max(date, na.rm = TRUE)) %>% 
  select(code = state, death) %>% 
  inner_join(code_names) %>% 
  inner_join(st_pop_2019) %>% 
  inner_join(pop_dens) %>% 
  inner_join(proj_sum) %>% 
  mutate(death_pm = death / pop_2019 * 1000000,
         death_3wk_proj_tot_pm = death_3wk_proj + death_pm) %>% 
  arrange(desc(death_3wk_proj_tot_pm)) %>%
  slice_max(order_by = death_pm, n = 15) %>%
  select(code, death, Density, death_3wk_proj, death_pm, death_3wk_proj_tot_pm) %>% 
  gather(key = "time_code", value = "death_pm", 4:5) %>% 
  ggplot(mapping = aes(x = reorder(code, desc(death_pm)), y = death_pm, fill = Density)) +
  geom_col(mapping = aes(color = time_code), size = 1) +
  scale_fill_gradient2(low = "white", mid = "white", high = "dodgerblue") +
  labs(x = "State", y = "COVID-19 deaths per million residents", fill = "population\ndensity", title = "States with high COVID-19 death rates may be dense or sparse", subtitle = str_c("COVID-19 deaths per million residents as of ", max(my_data$as_of, na.rm = TRUE))) +
  theme_bw() +
  # geom_label(mapping = aes(y = death_3wk_proj_tot_pm, label = death), fill = "lightgray") +
  scale_colour_discrete(type = c("lightgray", "dodgerblue"))

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
weekly_data %>% 
  filter(death_weekly_pm > quantile(weekly_data$death_weekly_pm, probs = 0.7, na.rm = TRUE) |
           # death_weekly_pm < quantile(weekly_data$death_weekly_pm, probs = 0.2, na.rm = TRUE) |
           code == "CA") %>%
  ggplot(mapping = aes(x = reorder(x = code, X = desc(death_weekly_pm)), y = death_weekly_pm, fill = reg_2)) +
  geom_col() +
  theme_bw() +
  theme(legend.title = element_blank()) +
  labs(x = "Date", y = "Deaths per million per week", title = "NM, PA, and AR are atop death rank", subtitle = str_c("Week ending ", max(weekly_data$wk_ending))) +
  scale_fill_brewer(palette="Dark2")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
weekly_data %>% 
  filter(case_weekly_pm > quantile(weekly_data$case_weekly_pm, probs = 0.7, na.rm = TRUE) |
           # case_weekly_pm < quantile(weekly_data$case_weekly_pm, probs = 0.2, na.rm = TRUE) |
           code == "CA") %>%
  ggplot(mapping = aes(x = reorder(x = code, X = desc(case_weekly_pm)), y = case_weekly_pm, fill = pos_rate)) +
  geom_col(color = "darkgray", size = 1) +
  theme_bw() +
  labs(x = NULL, y = "cases per million per week", title = "California led the nation in cases per capita for the first time", subtitle = str_c("It had ", weekly_data[code == "CA", case_weekly]," COVID-19 cases in the week ending ", max(weekly_data$wk_ending)), fill = "Pos. rate") +
  scale_fill_gradient2(low = "white", mid = "white", high = "dodgerblue")



```


```{r echo=FALSE, message=FALSE, warning=FALSE}
proj_sum %>%
  filter(death_3wk_proj > quantile(proj_sum$death_3wk_proj, 0.7) |
           # death_3wk_proj < quantile(proj_sum$death_3wk_proj, 0.2) |
           code == "CA") %>% 
  ggplot(mapping = aes(x = reorder(code, desc(death_3wk_proj)), y = death_3wk_proj, color = reg_2, fill = reg_2)) +
  geom_col(alpha = 0.2, linetype = "dashed", size = 1) +
  theme_bw() +
  theme(legend.title = element_blank()) +
  labs(title = "Northeast states may see an increase in deaths soon", subtitle = str_c("Projected deaths for three weeks starting ", max(my_data$as_of, na.rm = TRUE) + days(1)), x = NULL, y = "Projected deaths per million the next 3 weeks") +
  scale_fill_brewer(palette = "Dark2") +
  scale_color_brewer(palette = "Dark2")

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
print(str_c("Calculated: ", Sys.time(), " using ", Sys.Date() - ymd(max(all_data[,date])), "-day-old state public health data from ", ymd(max(all_data[,date]))))
```
