---
title: "When you fly affects delay"
output: html_notebook
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r eruptions, echo=FALSE, message=FALSE, warning=FALSE}
library(shiny); library(lubridate); library(tidyverse); library(ggthemes)

ui <- bootstrapPage( ## Define the UI
  dateInput(inputId = 'fly_date',
            label = 'Flight date',
            value = NULL,
            min = NULL,
            max = NULL,
            format = "yyyy-mm-dd",
            startview = "month",
            weekstart = 0,
            language = "en",
            width = NULL,
            autoclose = TRUE,
            datesdisabled = NULL,
            daysofweekdisabled = NULL),
  sliderInput(inputId = 'hr', label = 'Flight hour: ', min = 0, max = 23, value = 12, width = '100%'),
  sliderInput(inputId = 'min', label = 'Flight minute: ', min = 0, max = 59, value = 30, width = '100%'),
  plotOutput('plot')
)

server <- function(input, output) { ## Define the server code
  output$plot <- renderPlot({
    
    coef <- tibble(mn = c(3.85236934,
                          -0.06363243,
                          -0.05417439,
                          -0.06181426,
                          -0.12503443,
                          -0.17237966,
                          -0.10804876,
                          -0.04541431,
                          -0.17399921),
                   se = c(0.0121161721,
                          0.0008861738,
                          0.0020117717,
                          0.0135075053,
                          0.0151832949,
                          0.0140442096,
                          0.0134079232,
                          0.0139179082,
                          0.0139245864))

    my_norm <- tibble(.rows = 10000)
    for(i in 1:9) my_norm[i] = rnorm(n = nrow(my_norm), mean = coef[[i, 1]], sd = coef[[i, 2]])

    my_pred <- my_norm %>%
      mutate(pred_delay = exp(V1 +
                                V2 * abs(input$hr + (input$min + 0.5) / 60 - 21.45) +
                                V3 * abs(month(ymd(input$fly_date)) + (day(ymd(input$fly_date)) - 0.5) /
                                           (days_in_month(ymd(input$fly_date))) - 5.31) +
                                V4 * (weekdays(ymd(input$fly_date)) == 'Monday') +
                                V5 * (weekdays(ymd(input$fly_date)) == 'Saturday') +
                                V6 * (weekdays(ymd(input$fly_date)) == 'Sunday') +
                                V7 * (weekdays(ymd(input$fly_date)) == 'Thursday') +
                                V8 * (weekdays(ymd(input$fly_date)) == 'Tuesday') +
                                V9 * (weekdays(ymd(input$fly_date)) == 'Wednesday')))
    
    mdn_pred = median(my_pred$pred_delay)
    
    p_on_time <- 1 /
      (1 + exp(-(-0.868973986936626 +
                   0.132485588024036 * abs(input$hr + (input$min + 0.5) / 60 - 21.45) +
                   0.0938310236036926 * abs(month(ymd(input$fly_date)) + (day(ymd(input$fly_date)) - 0.5) /
                                              (days_in_month(ymd(input$fly_date))) - 5.31) +
                   0.152317762763714 * (weekdays(ymd(input$fly_date)) == 'Monday') +
                   0.312356993431681 * (weekdays(ymd(input$fly_date)) == 'Saturday') +
                   0.323550415257237 * (weekdays(ymd(input$fly_date)) == 'Sunday') +
                   0.0979982073199806 * (weekdays(ymd(input$fly_date)) == 'Thursday') +
                   0.265313809910303 * (weekdays(ymd(input$fly_date)) == 'Tuesday') +
                   0.316247648362565 * (weekdays(ymd(input$fly_date)) == 'Wednesday'))))
    
    is_delayed <- if_else(p_on_time < runif(10000), ' Late departure ', ' Early or on-time departure ')
    
    my_pred %>%
      ggplot() +
      geom_histogram(mapping = aes(my_pred$pred_delay, fill = is_delayed, color = is_delayed), bin = 60) +
      ggtitle(paste(sep = '', 'You have a ',
                    round(100*p_on_time),
                    '% chance of flying on time'),
              paste('But if delayed expect to wait around',
                    round(mdn_pred),
                    'minutes')) +
      
      
      
      theme(axis.title.x = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
            axis.title.y = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
            legend.title = element_blank(),
            legend.position= 'bottom') +
      scale_fill_manual(values = c('lightgray','darkblue'), aesthetics = 'fill', breaks = c('', 'Best')) +
      scale_color_manual(values = c('darkgray','black'), aesthetics = 'color', breaks = c('', 'Best')) +
      xlab('departure delay in minutes')
    
    

  })
}
shinyApp(ui = ui, server = server) ## Return a Shiny app object 
```

